---
config:
  burrito:
    datastore:
      storage:
        mock: false
        s3:
          bucket: vriska-burrito-datastore
          usePathStyle: true

datastore:
  deployment:
    envFrom:
      - secretRef:
          name: datastore-backblaze

tenants:
  - namespace:
      create: true
      name: burrito-project-test
    serviceAccounts:
      - name: runner-project-test
