---
config:
  burrito:
    datastore:
      storage:
        mock: false
        s3:
          bucket: vriska-burrito-datastore
          usePathStyle: true

datastore:
  deployment:
    envFrom:
      - secretRef:
          name: datastore-backblaze
