---
config:
  burrito:
    datastore:
      storage:
        mock: true

tenants:
  - namespace:
      create: true
      name: burrito-project-test
    serviceAccounts:
      - name: runner-project-test
