kind: Cluster
name: vriska
kubernetes:
  version: v1.28.4
talos:
  version: v1.5.5
patches:
  - file: ../patches/cilium-override.yaml
    name: cilium-override
---
kind: ControlPlane
machines:
  - 4c4c4544-004a-4310-8042-b4c04f365132
---
kind: Workers
machines:
  - 4c4c4544-0043-4210-8035-b4c04f365132
---
# kind: Workers
# name: storage
# machines:
#   - <worker machine UUID>
# ---
kind: Machine
name: 4c4c4544-004a-4310-8042-b4c04f365132
install:
  disk: /dev/sda
patches:
  - file: ../patches/intel-ucode.yaml
    name: intel-ucode
---
kind: Machine
name: 4c4c4544-0043-4210-8035-b4c04f365132
install:
  disk: /dev/nvme0n1
patches:
  - file: ../patches/intel-ucode.yaml
    name: intel-ucode
