apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: onepassword
  namespace: argocd
spec:
  project: default
  source:
    chart: connect
    repoURL: https://1password.github.io/connect-helm-charts
    targetRevision: 1.11.0
    helm:
      releaseName: connect
      parameters:
      - name: "connect.credentialsName"
        value: "onepassword-connect-server-credentials"
  destination:
    server: "https://kubernetes.default.svc"
    namespace: onepassword
  syncPolicy:
    managedNamespaceMetadata:
      labels:
        pod-security.kubernetes.io/enforce: privileged
        pod-security.kubernetes.io/audit: privileged
        pod-security.kubernetes.io/warn: privileged
    syncOptions:
    - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
