---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/monitoring.coreos.com/servicemonitor_v1.json
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: qbittorrent-metrics
  namespace: prometheus
  labels:
    release: kube-prometheus-stack
spec:
  endpoints:
    - port: metrics
  namespaceSelector:
    matchNames:
      - qbittorrent
  selector:
    matchLabels:
      app.kubernetes.io/instance: qbittorrent
      app.kubernetes.io/name: qbittorrent
