---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/library/common/values.schema.json
controllers:
  qbittorrent:
    containers:
      app:
        image:
          repository: ghcr.io/linuxserver/qbittorrent
          tag: 5.0.4@sha256:911807d3bf0e59194b2aaf158e8c4fca719ada78523f9e5f9f94cde8d84b79ee
          pullPolicy: IfNotPresent
        env:
          TZ: "America/Chicago"
          PUID: 979
          PGID: 979
          WEBUI_PORT: 8080
          TORRENTING_PORT: 51820
      metrics:
        image:
          repository: caseyscarborough/qbittorrent-exporter
          tag: v1.3.5
          pullPolicy: IfNotPresent
        envFrom:
          - secretRef:
              name: qbittorrent-metrics-credentials
      gluetun:
        dependsOn: app
        image:
          repository: ghcr.io/qdm12/gluetun
          tag: v3.39.1
        env:
          VPN_SERVICE_PROVIDER: mullvad
          VPN_TYPE: wireguard
          SERVER_CITIES: "Chicago IL"
          UPDATER_PERIOD: 24h
          FIREWALL_INPUT_PORTS: "8080,17871"
        envFrom:
          - secretRef:
              name: gluetun-mullvad-credentials
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            add:
              - NET_ADMIN
        resources:
          requests:
            squat.ai/tun: "1"
          limits:
            squat.ai/tun: "1"

service:
  web:
    enabled: true
    controller: qbittorrent
    annotations:
      external-dns.alpha.kubernetes.io/hostname: qbittorrent.localdomain
    type: LoadBalancer
    ports:
      http:
        port: 80
        targetPort: 8080
  metrics:
    controller: qbittorrent
    ports:
      metrics:
        port: 17871

persistence:
  config:
    enabled: true
    type: persistentVolumeClaim
    storageClass: ceph-block
    size: 10Gi
    accessMode: ReadWriteOnce
    advancedMounts:
      qbittorrent:
        app:
          - path: /config
  media:
    enabled: true
    type: nfs
    server: new-peepums
    path: /volume1/media/staging/torrents
    advancedMounts:
      qbittorrent:
        app:
          - path: /data/staging/torrents
