---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/library/common/values.schema.json
controllers:
  qbittorrent:
    type: statefulset
    pod:
      securityContext:
        fsGroup: 979
        fsGroupChangePolicy: "OnRootMismatch"
    initContainers:
      coredns:
        image:
          repository: docker.io/coredns/coredns
          tag: 1.12.2
        args:
          - -conf
          - /etc/coredns/Corefile
        restartPolicy: Always
      gluetun-config-staging:
        image:
          repository: docker.io/busybox
          tag: 1.37.0
        command:
            - /bin/sh
            - -c
            - cp /staging/servers.json /gluetun/servers.json
      gluetun:
        dependsOn:
          - coredns
          - gluetun-config-staging
        image:
          repository: ghcr.io/qdm12/gluetun
          tag: v3.40.0
        restartPolicy: Always
        env:
          TZ: "America/Chicago"
          VPN_SERVICE_PROVIDER: mullvad
          VPN_TYPE: wireguard
          SERVER_CITIES: "Chicago IL"
          DOT: "off"
          DNS_ADDRESS: "127.0.0.2"
          FIREWALL_INPUT_PORTS: "8080,17871"
          FIREWALL_OUTBOUND_SUBNETS: "10.96.0.0/12,10.244.0.0/24" # Allow access to k8s subnets
        envFrom:
          - secretRef:
              name: gluetun-mullvad-credentials
        lifecycle:
          postStart:
            exec:
              command:
                - /bin/sh
                - -c
                - (ip rule del table 51820; ip -6 rule del table 51820) || true
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            add:
              - NET_ADMIN
        resources:
          requests:
            squat.ai/tun: "1"
          limits:
            squat.ai/tun: "1"
    containers:
      app:
        image:
          repository: ghcr.io/home-operations/qbittorrent
          tag: 5.1.0@sha256:37aefd713ba31d51255995261616f1144378887bc5f21665a0ebf851fb85f69a
          pullPolicy: IfNotPresent
        env:
          TZ: "America/Chicago"
          QBT_WEBUI_PORT: 8080
          QBT_TORRENTING_PORT: 51820
        securityContext:
          runAsUser: 979
          runAsGroup: 979
          runAsNonRoot: true
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          capabilities:
            drop:
              - ALL
      metrics:
        image:
          repository: caseyscarborough/qbittorrent-exporter
          tag: v1.3.5
          pullPolicy: IfNotPresent
        envFrom:
          - secretRef:
              name: qbittorrent-metrics-credentials

service:
  web:
    enabled: true
    controller: qbittorrent
    type: LoadBalancer
    ports:
      http:
        port: 80
        targetPort: 8080
  metrics:
    controller: qbittorrent
    ports:
      metrics:
        port: 17871

serviceMonitor:
  metrics:
    serviceName: qbittorrent-metrics
    endpoints:
      - port: metrics

route:
  qbittorrent:
    hostnames: ["qbittorrent.mcmahan.io"]
    parentRefs:
      - name: local
        namespace: traefik
        sectionName: websecure
    rules:
      - backendRefs:
          - identifier: web
            port: 80

persistence:
  coredns:
    enabled: true
    type: configMap
    name: coredns-configmap
    advancedMounts:
      qbittorrent:
        coredns:
          - path: /etc/coredns/Corefile
            subPath: Corefile
            readOnly: true
  gluetun-staging:
    enabled: true
    type: configMap
    name: gluetun-configmap
    advancedMounts:
      qbittorrent:
        gluetun-config-staging:
          - path: /staging/servers.json
            subPath: servers.json
            readOnly: true
  gluetun:
    enabled: true
    type: emptyDir
    advancedMounts:
      qbittorrent:
        gluetun-config-staging:
          - path: /gluetun
        gluetun:
          - path: /gluetun
  config:
    enabled: true
    existingClaim: qbittorrent-config
    advancedMounts:
      qbittorrent:
        app:
          - path: /config
  media:
    enabled: true
    type: nfs
    server: new-peepums
    path: /volume1/media/staging/torrents
    advancedMounts:
      qbittorrent:
        app:
          - path: /data/staging/torrents
