---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/library/common/values.schema.json
controllers:
  prune:
    type: cronjob
    cronjob: &cronJobSpec
      schedule: "@hourly"
      backoffLimit: 0
      concurrencyPolicy: Forbid
      failedJobsHistory: 1
      successfulJobsHistory: 1
    pod:
      restartPolicy: Never
    initContainers:
      tagging: &container
        image:
          repository: ghcr.io/buroa/qbtools
          tag: v0.21.0@sha256:3a60f001c3f5fd068ff38960fbf9db726fa59edf135b18cd50294230366c284e
        env:
          QBITTORRENT_HOST: qbittorrent-web.qbittorrent.svc.cluster.local
          QBITTORRENT_PORT: 80
        args:
          - tagging
          - --added-on
          - --expired
          - --last-activity
          - --sites
          - --unregistered
          - --not-linked
        resources:
          requests:
            memory: 128Mi
            cpu: 25m
          limits:
            memory: 256Mi
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          capabilities:
            drop:
              - ALL
    containers:
      expired:
        <<: *container
        args:
          - prune
          - --exclude-tag
          - added:1d
          - --include-tag
          - not-linked
          - --include-tag
          - expired
          - --with-data
      unregistered:
        <<: *container
        args:
          - prune
          - --exclude-tag
          - added:1d
          - --include-tag
          - unregistered
          - --with-data
  orphaned:
    type: cronjob
    cronjob:
      <<: *cronJobSpec
      schedule: "@daily"
    pod:
      restartPolicy: Never
    containers:
      app:
        <<: *container
        args:
          - orphaned
          - --exclude-pattern
          - "*_unpackerred*"
  reannounce:
    containers:
      app:
        <<: *container
        args:
          - reannounce
          - --process-seeding

defaultPodOptions:
  securityContext:
    runAsUser: 979
    runAsGroup: 979
    fsGroup: 979
    fsGroupChangePolicy: "OnRootMismatch"
    runAsNonRoot: true

persistence:
  config:
    enabled: true
    type: configMap
    name: qbtools-configmap
    globalMounts:
      - path: /config/config.yaml
        subPath: config.yaml
        readOnly: true
  media:
    enabled: true
    type: nfs
    server: new-peepums
    path: /volume1/media/staging/torrents
    globalMounts:
      - path: /data/staging/torrents
