---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/library/common/values.schema.json
controllers:
  qbittorrent:
    pod:
      securityContext:
        fsGroup: 979
        fsGroupChangePolicy: "OnRootMismatch"

    containers:
      app:
        image:
          repository: ghcr.io/linuxserver/qbittorrent
          tag: 5.0.3@sha256:1f08c56ecdf45d621f46966ec5f1d327e9f4075bdbe0e45e483a1b66f6b1d083
          pullPolicy: IfNotPresent
        env:
          TZ: "America/Chicago"
          PUID: 979
          PGID: 979
          WEBUI_PORT: 8080
          TORRENTING_PORT: 51820
        securityContext:
          readOnlyRootFilesystem: true
          capabilities:
            drop:
              - ALL
      metrics:
        image:
          repository: caseyscarborough/qbittorrent-exporter
          tag: v1.3.5
          pullPolicy: IfNotPresent
        envFrom:
          - secretRef:
              name: qbittorrent-metrics-credentials
      gluetun:
        dependsOn: app
        image:
          repository: ghcr.io/qdm12/gluetun
          tag: v3.39.1
        env:
          VPN_SERVICE_PROVIDER: mullvad
          VPN_TYPE: wireguard
          SERVER_CITIES: "Chicago IL"
          FIREWALL_INPUT_PORTS: "8080,17871"
        envFrom:
          - secretRef:
              name: gluetun-mullvad-credentials
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            add:
              - NET_ADMIN
        resources:
          requests:
            squat.ai/tun: "1"
          limits:
            squat.ai/tun: "1"

service:
  web:
    enabled: true
    controller: qbittorrent
    annotations:
      external-dns.alpha.kubernetes.io/hostname: qbittorrent.localdomain
    type: LoadBalancer
    ports:
      http:
        port: 80
        targetPort: 8080
  metrics:
    controller: qbittorrent
    ports:
      metrics:
        port: 17871

persistence:
  # https://docs.linuxserver.io/misc/read-only/
  run:
    enabled: true
    type: emptyDir
    medium: Memory
    advancedMounts:
      qbittorrent:
        app:
          - path: /run
  config:
    enabled: true
    type: persistentVolumeClaim
    storageClass: ceph-block
    size: 10Gi
    accessMode: ReadWriteOnce
    advancedMounts:
      qbittorrent:
        app:
          - path: /config
  media:
    enabled: true
    type: nfs
    server: new-peepums
    path: /volume1/media/staging/torrents
    advancedMounts:
      qbittorrent:
        app:
          - path: /data/staging/torrents
