---
controllers:
  main:
    pod:
      securityContext:
        fsGroup: 979
        fsGroupChangePolicy: "OnRootMismatch"

    containers:
      main:
        image:
          repository: ghcr.io/onedr0p/qbittorrent
          tag: 4.6.3
          pullPolicy: IfNotPresent
        env:
          TZ: "America/Chicago"
          QBITTORRENT__PORT: 8080
          QBITTORRENT__BT_PORT: 51820
        securityContext:
          runAsUser: 979
          runAsGroup: 979
          runAsNonRoot: true
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          capabilities:
            drop:
              - ALL
      metrics:
        image:
          repository: ghcr.io/esanchezm/prometheus-qbittorrent-exporter
          tag: v1.5.1
          pullPolicy: IfNotPresent
        env:
          QBITTORRENT_HOST: qbittorrent
          QBITTORRENT_PORT: 80
          EXPORTER_PORT: 9000
      gluetun:
        dependsOn: main
        image:
          repository: ghcr.io/qdm12/gluetun
          tag: v3.37.0
        env:
          VPN_SERVICE_PROVIDER: mullvad
          VPN_TYPE: wireguard
          SERVER_CITIES: "Chicago IL"
          ISP: Quadranet
          FIREWALL_INPUT_PORTS: "8080,9000"
        envFrom:
          - secretRef:
              name: gluetun-mullvad-credentials
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            add:
              - NET_ADMIN

service:
  main:
    annotations:
      external-dns.alpha.kubernetes.io/hostname: qbittorrent.localdomain
    type: LoadBalancer
    ports:
      http:
        port: 80
        targetPort: 8080
  metrics:
    controller: main
    ports:
      metrics:
        port: 9000

persistence:
  config:
    enabled: true
    type: persistentVolumeClaim
    storageClass: ceph-block
    size: 10Gi
    accessMode: ReadWriteOnce
    advancedMounts:
      main:
        main:
          - path: /config
  media:
    enabled: true
    type: nfs
    server: peepums
    path: /pool01/media/staging/torrents
    advancedMounts:
      main:
        main:
          - path: /data/staging/torrents
