---
# yaml-language-server: $schema=https://raw.githubusercontent.com/authelia/chartrepo/master/charts/authelia/values.schema.json
ingress:
  gatewayAPI:
    enabled: true
    parentRefs:
      - name: remote
        namespace: traefik
        sectionName: websecure

  traefikCRD:
    enabled: true
    disableIngressRoute: true
    middlewares:
      auth:
        enableMaxResponseBodySize: true

secret:
  additionalSecrets:
    authelia-cluster:
      items:
        - key: password
          path: postgres-password

configMap:
  theme: dark

  authentication_backend:
    file:
      enabled: true

  notifier:
    filesystem:
      enabled: true
      filename: /config/notification.txt

  session:
    cookies:
      - domain: mcmahan.io
        subdomain: auth

  storage:
    postgres:
      enabled: true
      address: tcp://authelia-cluster-rw.authelia.svc.cluster.local:5432
      database: authelia
      username: authelia
      password:
        secret_name: authelia-cluster
        path: postgres-password
