---
apiVersion: volsync.backube/v1alpha1
kind: ReplicationDestination
metadata:
  namespace: sonarr
  name: sonarr-config-restore
spec:
  trigger:
    manual: restore-once
  restic:
    repository: sonarr-volsync-backblaze
    destinationPVC: sonarr-config
    copyMethod: Direct
    moverSecurityContext:
      runAsUser: 568
      runAsGroup: 568
      fsGroup: 568
