apiVersion: metal.sidero.dev/v1alpha1
kind: Server
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"metal.sidero.dev/v1alpha1","kind":"Server","metadata":{"annotations":{},"creationTimestamp":"2023-07-04T18:15:54Z","finalizers":["storage.finalizers.server.k8s.io"],"generation":1,"name":"4c4c4544-0039-4a10-8048-b9c04f305432","resourceVersion":"388354","uid":"30c29b2e-b4e3-4902-bb09-08b760ae8f82"},"spec":{"accepted":true,"cpu":{"manufacturer":"Intel(R) Corporation","version":"Intel(R) Core(TM) i5-8500T CPU @ 2.10GHz"},"hostname":"192.168.8.100","system":{"family":"Unknown","manufacturer":"OptiPlex","productName":"Dell Inc.","serialNumber":"085A","skuNumber":"99JH0T2","version":"OptiPlex 7060"}},"status":{"addresses":[{"address":"192.168.8.100","type":"InternalIP"}],"power":"on"}}
  creationTimestamp: "2023-07-04T18:15:54Z"
  finalizers:
  - storage.finalizers.server.k8s.io
  generation: 2
  name: 4c4c4544-0039-4a10-8048-b9c04f305432
  resourceVersion: "391212"
  uid: 30c29b2e-b4e3-4902-bb09-08b760ae8f82
spec:
  accepted: true
  cpu:
    manufacturer: Intel(R) Corporation
    version: Intel(R) Core(TM) i5-8500T CPU @ 2.10GHz
  hostname: 192.168.8.100
  system:
    family: Unknown
    manufacturer: OptiPlex
    productName: Dell Inc.
    serialNumber: 085A
    skuNumber: 99JH0T2
    version: OptiPlex 7060
  configPatches:
    - op: replace
      path: /machine/install/disk
      value: /dev/nvme0n1
status:
  addresses:
  - address: 192.168.8.100
    type: InternalIP
  conditions:
  - lastTransitionTime: "2023-07-04T18:25:33Z"
    status: "True"
    type: PXEBooted
  - lastTransitionTime: "2023-07-04T18:24:55Z"
    status: "True"
    type: PowerCycle
  inUse: true
  isClean: false
  power: "on"
  ready: true
