apiVersion: metal.sidero.dev/v1alpha1
kind: Server
metadata:
  creationTimestamp: "2023-07-04T21:22:52Z"
  finalizers:
  - storage.finalizers.server.k8s.io
  generation: 1
  name: 4c4c4544-0052-4610-8054-b3c04f4e5932
  resourceVersion: "443733"
  uid: 710d1deb-9c32-42b1-9cce-196b790d8892
spec:
  accepted: true
  cpu:
    manufacturer: Intel(R) Corporation
    version: Intel(R) Core(TM) i5-8600T CPU @ 2.30GHz
  hostname: k8s-worker-2
  system:
    family: Unknown
    manufacturer: OptiPlex
    productName: Dell Inc.
    serialNumber: 085A
    skuNumber: 3RFTNY2
    version: OptiPlex 7060
  configPatches:
    - op: replace
      path: /machine/install/disk
      value: /dev/nvme0n1
status:
  addresses:
  - address: 192.168.8.29
    type: InternalIP
  power: "on"
