---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/library/common/values.schema.json
controllers:
  quailscale:
    pod:
      securityContext:
        fsGroup: 979
        fsGroupChangePolicy: "OnRootMismatch"

    containers:
      tailscale:
        image:
          repository: tailscale/tailscale
          tag: v1.86.2
          pullPolicy: IfNotPresent
        env:
          TS_STATE_DIR: "/var/lib/tailscale"
          TS_KUBE_SECRET: ""
          TS_HOSTNAME: "quailscale"
          TS_EXTRA_ARGS: "--ssh"
        envFrom:
          - secretRef:
              name: tailscale-authkey
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            add:
              - NET_ADMIN
        resources:
          requests:
            squat.ai/tun: "1"
          limits:
            squat.ai/tun: "1"

persistence:
  state:
    enabled: true
    existingClaim: quailscale-tailscale-state
    advancedMounts:
      quailscale:
        tailscale:
          - path: /var/lib/tailscale
  books:
    enabled: true
    type: nfs
    server: new-peepums
    path: '/volume1/media/books/Calibre Library'
    advancedMounts:
      quailscale:
        tailscale:
          - path: /share/books
            readOnly: true
  anime:
    enabled: true
    type: nfs
    server: new-peepums
    path: '/volume1/media/plex/anime'
    advancedMounts:
      quailscale:
        tailscale:
          - path: /share/anime
            readOnly: true
  movies:
    enabled: true
    type: nfs
    server: new-peepums
    path: '/volume1/media/plex/movies'
    advancedMounts:
      quailscale:
        tailscale:
          - path: /share/movies
            readOnly: true
  tv:
    enabled: true
    type: nfs
    server: new-peepums
    path: '/volume1/media/plex/tv'
    advancedMounts:
      quailscale:
        tailscale:
          - path: /share/tv
            readOnly: true
