---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/library/common/values.schema.json
controllers:
  taildrop:
    pod:
      securityContext:
        fsGroup: 979
        fsGroupChangePolicy: "OnRootMismatch"

    containers:
      tailscale:
        image:
          repository: tailscale/tailscale
          tag: v1.76.1
          pullPolicy: IfNotPresent
        env:
          TS_STATE_DIR: "/var/lib/tailscale"
          TS_KUBE_SECRET: ""
          TS_HOSTNAME: "quailscale"
          TS_EXTRA_ARGS: "--ssh"
        envFrom:
          - secretRef:
              name: tailscale-authkey
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            add:
              - NET_ADMIN

persistence:
  state:
    enabled: true
    type: persistentVolumeClaim
    storageClass: ceph-block
    size: 1Gi
    accessMode: ReadWriteOnce
    advancedMounts:
      taildrop:
        tailscale:
          - path: /var/lib/tailscale
  books:
    enabled: true
    type: nfs
    server: new-peepums
    path: '/volume1/media/books/Calibre Library'
    advancedMounts:
      taildrop:
        tailscale:
          - path: /share/books
            readOnly: true
