---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/library/common/values.schema.json
controllers:
  quailscale:
    pod:
      securityContext:
        fsGroup: 979
        fsGroupChangePolicy: "OnRootMismatch"

    containers:
      busybox:
        image:
          repository: busybox
          tag: 1.37.0@sha256:37f7b378a29ceb4c551b1b5582e27747b855bbfaa73fa11914fe0df028dc581f
          pullPolicy: IfNotPresent
        command: ["/bin/sh", "-c", "tail -f /dev/null"]
        securityContext:
          runAsNonRoot: true
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true

service:
  tailscale:
    enabled: true
    controller: quailscale
    annotations:
      external-dns.alpha.kubernetes.io/hostname: qbittorrent.localdomain
    type: LoadBalancer
    loadBalancerClass: tailscale
    ports:
      tailscale:
        port: 8022

persistence:
  books:
    enabled: true
    type: nfs
    server: new-peepums
    path: '/volume1/media/books/Calibre Library'
    advancedMounts:
      quailscale:
        tailscale:
          - path: /share/books
            readOnly: true
  anime:
    enabled: true
    type: nfs
    server: new-peepums
    path: '/volume1/media/plex/anime'
    advancedMounts:
      quailscale:
        tailscale:
          - path: /share/anime
            readOnly: true
  movies:
    enabled: true
    type: nfs
    server: new-peepums
    path: '/volume1/media/plex/movies'
    advancedMounts:
      quailscale:
        tailscale:
          - path: /share/movies
            readOnly: true
  tv:
    enabled: true
    type: nfs
    server: new-peepums
    path: '/volume1/media/plex/tv'
    advancedMounts:
      quailscale:
        tailscale:
          - path: /share/tv
            readOnly: true
