---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/library/common/values.schema.json
controllers:
  quailscale:
    pod:
      securityContext:
        fsGroup: 979
        fsGroupChangePolicy: "OnRootMismatch"

    containers:
      alpine:
        image:
          repository: nixery.dev/shell/coreutils
          tag: latest
          pullPolicy: Always
        command: ["/bin/bash", "-c", "sleep infinity"]
        securityContext:
          runAsUser: 979
          runAsGroup: 979
          runAsNonRoot: true
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true

service:
  tailscale:
    enabled: true
    controller: quailscale
    annotations:
      external-dns.alpha.kubernetes.io/hostname: qbittorrent.localdomain
    type: LoadBalancer
    loadBalancerClass: tailscale
    ports:
      tailscale:
        port: 8022

persistence:
  books:
    enabled: true
    type: nfs
    server: new-peepums
    path: '/volume1/media/books/Calibre Library'
    advancedMounts:
      quailscale:
        tailscale:
          - path: /share/books
            readOnly: true
  anime:
    enabled: true
    type: nfs
    server: new-peepums
    path: '/volume1/media/plex/anime'
    advancedMounts:
      quailscale:
        tailscale:
          - path: /share/anime
            readOnly: true
  movies:
    enabled: true
    type: nfs
    server: new-peepums
    path: '/volume1/media/plex/movies'
    advancedMounts:
      quailscale:
        tailscale:
          - path: /share/movies
            readOnly: true
  tv:
    enabled: true
    type: nfs
    server: new-peepums
    path: '/volume1/media/plex/tv'
    advancedMounts:
      quailscale:
        tailscale:
          - path: /share/tv
            readOnly: true
