---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: plex-volsync-backblaze
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: default
  target:
    name: plex-volsync-backblaze
    template:
      engineVersion: v2
      data:
        RESTIC_REPOSITORY: "s3:https://{{ .endpoint }}/vriska-pvc-plex"
        RESTIC_PASSWORD: "{{ .resticPassword }}"
        AWS_ACCESS_KEY_ID: "{{ .keyID }}"
        AWS_SECRET_ACCESS_KEY: "{{ .applicationKey }}"
  dataFrom:
    - extract:
        conversionStrategy: Default
        decodingStrategy: None
        key: volsync-backblaze
        metadataPolicy: None
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/volsync.backube/replicationsource_v1alpha1.json
apiVersion: volsync.backube/v1alpha1
kind: ReplicationSource
metadata:
  name: plex-backblaze
spec:
  sourcePVC: plex-config
  trigger:
    schedule: "0 0 * * *"
  restic:
    copyMethod: Snapshot
    cacheCapacity: 10Gi
    pruneIntervalDays: 7
    repository: plex-volsync-backblaze
    volumeSnapshotClassName: ceph-block
    moverSecurityContext:
      runAsUser: 979
      runAsGroup: 979
      fsGroup: 979
    retain:
      daily: 7
    unlock: "44a5a3a"
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/volsync.backube/replicationdestination_v1alpha1.json
apiVersion: volsync.backube/v1alpha1
kind: ReplicationDestination
metadata:
  namespace: plex
  name: plex-config-dest
spec:
  trigger:
    manual: restore-once
  restic:
    repository: plex-volsync-backblaze
    copyMethod: Snapshot
    storageClassName: ceph-block
    accessModes: [ReadWriteOnce]
    capacity: 30Gi
    moverSecurityContext:
      runAsUser: 979
      runAsGroup: 979
      fsGroup: 979
    enableFileDeletion: true
    cleanupCachePVC: true
    cleanupTempPVC: true
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: plex-config
spec:
  accessModes: [ReadWriteOnce]
  dataSourceRef:
    kind: ReplicationDestination
    apiGroup: volsync.backube
    name: plex-config-dest
  resources:
    requests:
      storage: 30Gi
  storageClassName: ceph-block
