---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/library/common/values.schema.json
controllers:
  webtop:
    containers:
      app:
        image:
          repository: lscr.io/linuxserver/webtop
          tag: fedora-kde@sha256:19c9b281896ae86b8f03ac9455ba1102102711f82fad8761d50fdbd6db065555
          pullPolicy: IfNotPresent
        env:
          - name: TZ
            value: "America/Chicago"
          - name: CUSTOM_USER
            valueFrom:
              secretKeyRef:
                name: webtop-user-secret
                key: username
          - name: PASSWORD
            valueFrom:
              secretKeyRef:
                name: webtop-user-secret
                key: password
        resources:
          requests:
            gpu.intel.com/i915: 1
          limits:
            gpu.intel.com/i915: 1

service:
  web:
    enabled: true
    controller: webtop
    annotations:
      external-dns.alpha.kubernetes.io/hostname: webtop.localdomain
    type: LoadBalancer
    ports:
      http:
        port: 80
        targetPort: 3000
