apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - "namespace.yaml"

helmCharts:
  - name: ark-cluster
    repo: https://sickhub.github.io/ark-server-charts
    version: 0.1.14
    releaseName: ark-cluster
    namespace: ark
    valuesFile: values.yaml

patches:
- patch: |-
    apiVersion: v1
    kind: Service
    metadata:
      name: ark-cluster-peeps-tcp
    spec:
      loadBalancerIP: "192.168.8.175"
  target:
    kind: Service
    name: "ark-cluster-peeps-tcp"
- patch: |-
    apiVersion: v1
    kind: Service
    metadata:
      name: ark-cluster-peeps-udp
    spec:
      loadBalancerIP: "192.168.8.175"
  target:
    kind: Service
    name: "ark-cluster-peeps-udp"