apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - "namespace.yaml"

helmCharts:
  - name: ark-cluster
    repo: https://sickhub.github.io/ark-server-charts
    version: 0.1.14
    releaseName: ark-cluster
    namespace: ark
    valuesFile: values.yaml
