replicaCount: 1
clusterName: ark

servers:
  peeps:
    customConfigMap:
      GameUserSettingsIni: |
        [/Script/ShooterGame.ShooterGameUserSettings]
        Version=5
        [ServerSettings]
        HarvestAmountMultiplier=6.00000
        HarvestHealthMultiplier=6.00000
    updateOnStart: true
    sessionName: "peeps"
    message: "Welcome to peeps"
    map: TheIsland
    password: ""
    maxPlayers: 10
    ports:
      queryudp: 27015
      gameudp: 7770
      rcon: 32330
    mods:
      - "558651608"
      - "719928795"
      - "1428596566"
      - "1999447172"
      - "751991809"
      - "761535755"

resources:
  requests:
    cpu: 1
    memory: 8Gi
  limits:
    cpu: 2
    memory: 16Gi

extraEnvVars:
  - name: am_ark_GameUserSettingsIniFile
    value: /arkconfig/GameUserSettings.ini
  - name: am_ark_HarvestAmountMultiplier
    value: 6
  - name: am_ark_HarvestHealthMultiplier
    value: 6

service:
  enabled: true
  type: LoadBalancer
  loadBalancerIP: "192.168.8.175"
  metallb_shared_ip: true

persistence:
  enabled: true
  game:
    storageClass: ceph-filesystem
    accessModes:
    - ReadWriteOnce
  cluster:
    storageClass: ceph-filesystem
  save:
    storageClass: ceph-filesystem

startupProbe:
  # allow plenty of time for installation if necessary
  failureThreshold: 480

securityContext:
  runAsUser: 1000
  fsGroup: 1000
