apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: cloudflare
spec:
  acme:
    solvers:
    - dns01:
        cloudflare:
          apiTokenSecretRef:
            name: cloudflare-certmanager-token
            key: token
