apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- cloudflare-certmanager-token.yaml

helmCharts:
- name: cert-manager
  repo: https://charts.jetstack.io
  version: 1.12.2
  releaseName: cert-manager
  namespace: cert-manager
  valuesInline:
    prometheus:
      enabled: true
      servicemonitor:
        enabled: true
