---
# yaml-language-server: $schema=https://raw.githubusercontent.com/recyclarr/recyclarr/master/schemas/config-schema.json
sonarr:
  sonarr:
    base_url: http://sonarr-web.sonarr.svc
    api_key: !env_var SONARR_API_KEY

    media_naming:
      series: default
      season: default
      episodes:
        rename: true
        standard: default
        daily: default
        anime: default

    delete_old_custom_formats: true

    quality_definition:
      type: series

    quality_profiles:
      - name: UHD 2160p
        trash_id: e58cf4e090184db3b3d7c79c1a9e9b4a # Base Profile
        reset_unmatched_scores:
          enabled: true
        quality_sort: top
        qualities:
          - name: Bluray-2160p Remux
          - name: Bluray-2160p
          - name: WEB 2160p
            qualities:
              - WEBDL-2160p
              - WEBRip-2160p
          - name: HDTV-2160p
          - name: Bluray-1080p Remux
          - name: Bluray-1080p
          - name: WEB 1080p
            qualities:
              - WEBDL-1080p
              - WEBRip-1080p
          - name: HDTV-1080p
          - name: Bluray-720p
          - name: WEB 720p
            qualities:
              - WEBDL-720p
              - WEBRip-720p
          - name: HDTV-720p
          - name: Bluray-480p
          - name: WEB 480p
            qualities:
              - WEBDL-480p
              - WEBRip-480p
          - name: DVD
          - name: SDTV
      - name: HD 1080p
        trash_id: e58cf4e090184db3b3d7c79c1a9e9b4a # Base Profile
        reset_unmatched_scores:
          enabled: true
        upgrade:
          allowed: true
          until_quality: Bluray-1080p
          until_score: 10000
        min_format_score: 0
        quality_sort: top
        qualities:
          - name: Bluray-1080p
          - name: WEB 1080p
            qualities:
              - WEBDL-1080p
              - WEBRip-1080p
          - name: HDTV-1080p
          - name: Bluray-720p
          - name: WEB 720p
            qualities:
              - WEBDL-720p
              - WEBRip-720p
          - name: HDTV-720p
          - name: Bluray-480p
          - name: WEB 480p
            qualities:
              - WEBDL-480p
              - WEBRip-480p
          - name: DVD
          - name: SDTV
      - name: HD 1080p - Anime
        trash_id: 20e0fc959f1f1704bed501f23bdae76f # [Anime] Remux-1080p
        reset_unmatched_scores:
          enabled: true
        min_format_score: 0
        score_set: anime-sonarr
        quality_sort: top
        qualities:
          - name: Bluray-1080p
            qualities:
              - Bluray-1080p Remux
              - Bluray-1080p
          - name: WEB 1080p
            qualities:
              - WEBDL-1080p
              - WEBRip-1080p
              - HDTV-1080p
          - name: Bluray-720p
          - name: WEB 720p
            qualities:
              - WEBDL-720p
              - WEBRip-720p
              - HDTV-720p
          - name: Bluray-480p
          - name: WEB 480p
            qualities:
              - WEBDL-480p
              - WEBRip-480p
          - name: DVD
          - name: SDTV

    custom_format_groups:
      add:
        - trash_id: d776a1ea912a117d66d83b880ff2055d # [HDR Formats] DV (w/o HDR fallback)

        - trash_id: e1053c0ef622df3749fa43c22865663a # [HDR Formats] SDR
          select:
            - 2016d1676f5ee13a5b7257ff86ac9a93 # SDR

        - trash_id: b4a4353e3b3e6789dbef07677ff23686 # [Release Groups] HQ
          select_all: true

        - trash_id: 35fb4585dcd9e2a5ac732e4309f5a45a # [Streaming Services] Asian

        - trash_id: f60f4401ce880aad62e9d21c8bb6b91a # [Streaming Services] Dutch

        - trash_id: ddab3095a5d2f436f369263840af34f9 # [Streaming Services] UK

        - trash_id: 7832db22b71ab669458c17a2850d6913 # [Streaming Services] Miscellaneous
          select_all: true

        - trash_id: a4a95b9f7bdf10dcb005e765155e4d24 # [Optional] Series Versions
          select_all: true

        - trash_id: 158188097a58d7687dee647e04af0da3 # [Optional] Golden Rule HD
          assign_scores_to:
            - name: HD 1080p

        - trash_id: e3f37512790f00d0e89e54fe5e790d1c # [Optional] Golden Rule UHD
          assign_scores_to:
            - name: UHD 2160p

        - trash_id: f4a0410a1df109a66d6e47dcadcce014 # [Optional] Miscellaneous
          select:
            - d7c747094a7c65f4c2de083c24899e8b # FreeLeech

        - trash_id: 59c3af66780d08332fdc64e68297098f # [Unwanted] Unwanted Formats
          select_all: true

    custom_formats:
      - trash_ids:
          - 418f50b10f1907201b6cfdf881f467b7 # Anime Dual Audio
        assign_scores_to:
          - name: HD 1080p - Anime
            score: 10

radarr:
  radarr:
    base_url: http://radarr-web.radarr.svc
    api_key: !env_var RADARR_API_KEY

    media_naming:
      folder: default
      movie:
        rename: true
        standard: plex-imdb

    delete_old_custom_formats: true

    quality_definition:
      type: movie

    quality_profiles:
      - name: UHD 2160p
        trash_id: 92e9a65a52ae48478fb8e9f34238d823 # Base Profile
        reset_unmatched_scores:
          enabled: true
        quality_sort: top
        qualities:
          - name: Remux-2160p
          - name: Bluray-2160p
          - name: WEB 2160p
            qualities:
              - WEBDL-2160p
              - WEBRip-2160p
          - name: HDTV-2160p
          - name: Remux-1080p
          - name: Bluray-1080p
          - name: WEB 1080p
            qualities:
              - WEBDL-1080p
              - WEBRip-1080p
          - name: HDTV-1080p
          - name: Bluray-720p
          - name: WEB 720p
            qualities:
              - WEBDL-720p
              - WEBRip-720p
          - name: HDTV-720p
          - name: Bluray-576p
          - name: Bluray-480p
          - name: WEB 480p
            qualities:
              - WEBDL-480p
              - WEBRip-480p
          - name: DVD
          - name: SDTV
      - name: HD 1080p
        trash_id: 92e9a65a52ae48478fb8e9f34238d823 # Base Profile
        reset_unmatched_scores:
          enabled: true
        quality_sort: top
        qualities:
          - name: Bluray-1080p
          - name: WEB 1080p
            qualities:
              - WEBDL-1080p
              - WEBRip-1080p
          - name: HDTV-1080p
          - name: Bluray-720p
          - name: WEB 720p
            qualities:
              - WEBDL-720p
              - WEBRip-720p
          - name: HDTV-720p
          - name: Bluray-576p
          - name: Bluray-480p
          - name: WEB 480p
            qualities:
              - WEBDL-480p
              - WEBRip-480p
          - name: DVD
          - name: SDTV
      - name: HD 1080p - Anime
        trash_id: 722b624f9af1e492284c4bc842153a38 # [Anime] Remux-1080p
        reset_unmatched_scores:
          enabled: true
        min_format_score: 0
        score_set: anime-radarr
        quality_sort: top
        qualities:
          - name: Remux-1080p
            qualities:
              - Bluray-1080p
              - Remux-1080p
          - name: WEB 1080p
            qualities:
              - WEBDL-1080p
              - WEBRip-1080p
              - HDTV-1080p
          - name: Bluray-720p
          - name: WEB 720p
            qualities:
              - WEBDL-720p
              - WEBRip-720p
              - HDTV-720p
          - name: Bluray-576p
          - name: Bluray-480p
          - name: WEB 480p
            qualities:
              - WEBDL-480p
              - WEBRip-480p
          - name: DVD
          - name: SDTV

    custom_format_groups:
      add:
        - trash_id: 7fc2751eef7e6bdc70b74136e5e35c76 # [HDR Formats] DV (w/o HDR fallback)

        - trash_id: 47f0d69750de9e16855915fa73bb7b08 # [HDR Formats] SDR
          select:
            - 9c38ebb7384dada637be8899efa68e6f # SDR

        - trash_id: b2f2af430f73f3ad1f9948f33e0f0cf8 # [Release Groups] HQ
          select_all: true

        - trash_id: f4f1474b963b24cf983455743aa9906c # [Optional] Movie Versions
          select_all: true

        - trash_id: f8bf8eab4617f12dfdbd16303d8da245 # [Optional] Golden Rule HD
          assign_scores_to:
            - name: HD 1080p

        - trash_id: ff204bbcecdd487d1cefcefdbf0c278d # [Optional] Golden Rule UHD
          assign_scores_to:
            - name: UHD 2160p

        - trash_id: 9337080378236ce4c0b183e35790d2a7 # [Optional] Miscellaneous
          select:
            - 0d91270a7255a1e388fa85e959f359d8 # FreeLeech

        - trash_id: a3ac6af01d78e4f21fcb75f601ac96df # [Unwanted] Unwanted Formats
          select_all: true

    custom_formats:
      - trash_ids:
          - 4a3b087eea2ce012fcc1ce319259a3be # Anime Dual Audio
        assign_scores_to:
          - name: HD 1080p - Anime
            score: 10
