---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml

helmCharts:
  - name: prometheus-smartctl-exporter
    repo: https://prometheus-community.github.io/helm-charts
    version: 0.15.1
    releaseName: smartctl-exporter
    namespace: smartctl
    valuesInline:
      serviceMonitor:
        enabled: true
