---
ollama:
  gpu:
    enabled: true
  models:
    pull:
      - qwen2.5-coder
      - qwen3.5:35b
  clean: true

httpRoute:
  enabled: true
  hostnames: ["ollama.mcmahan.io"]
  parentRefs:
    - name: local
      namespace: traefik
      sectionName: websecure

persistentVolume:
  enabled: true
  size: 120Gi
  storageClass: ceph-block
