---
ollama:
  gpu:
    enabled: true
  models:
    pull:
      - gemma3
      - mistral
      - qwen3-coder

httpRoute:
  enabled: true
  hostnames: ["ollama.mcmahan.io"]
  parentRefs:
    - name: local
      namespace: traefik
      sectionName: websecure
