name: pxe
services:
  dnsmasq:
    cap_add:
      - NET_ADMIN
    network_mode: host
    container_name: dnsmasq
    image: quay.io/poseidon/dnsmasq
    restart: always
    command: >
      -d
      -q
      --dhcp-range=192.168.8.1,proxy,255.255.255.0
      --enable-tftp
      --tftp-root=/var/lib/tftpboot
      --dhcp-userclass=set:ipxe,iPXE
      --pxe-service=tag:#ipxe,x86PC,"PXE chainload to iPXE",undionly.kpxe
      --pxe-service=tag:ipxe,x86PC,"iPXE",http://192.168.8.254:8080/boot.ipxe
      --pxe-service=tag:#ipxe,X86-64_EFI,"PXE chainload to iPXE UEFI",ipxe.efi
      --pxe-service=tag:ipxe,X86-64_EFI,"iPXE UEFI",http://192.168.8.254:8080/boot.ipxe
      --log-queries
      --log-dhcp
  matchbox:
    network_mode: host
    container_name: matchbox
    image: quay.io/poseidon/matchbox
    restart: always
    volumes:
      - ./volumes/matchbox/var/lib/matchbox:/var/lib/matchbox:Z
      - ./etc/matchbox:/etc/matchbox:Z,ro
    command: >
      -address=0.0.0.0:8080
      -rpc-address=0.0.0.0:8081
      -log-level=debug
