---
apiVersion: v1alpha1
kind: KubeNodeConfig
taints:
  node-role.kubernetes.io/control-plane:
    $patch: delete
labels:
  node.kubernetes.io/exclude-from-external-load-balancers:
    $patch: delete
