---
image:
  repository: ghcr.io/gethomepage/homepage
  tag: v1.2.0@sha256:5e6bcbb595c4e857540577135e0f8b3ffc2e97c23d6e0ddc7df183de5bfdd442

enableRbac: true

serviceAccount:
  create: true

service:
  main:
    annotations:
      external-dns.alpha.kubernetes.io/hostname: homepage.localdomain
    type: LoadBalancer
    ports:
      http:
        port: 80
        targetPort: 3000

controller:
  strategy: RollingUpdate
  rollingUpdate:
    maxSurge: 25%
    maxUnavailable: 25%

config:
  bookmarks: []
  services:
    - Home:
        - UniFi Controller:
            icon: unifi.svg
            url: https://unifi.ui.com/consoles/bb5782ea-0cd7-4a31-b4e0-5566c6a25a07
            description: UniFi Controller
            widget:
              type: unifi
              url: https://192.168.0.1
              username: {{HOMEPAGE_VAR_UNIFI_USER}}
              password: {{HOMEPAGE_VAR_UNIFI_PASS}}
  widgets:
    - datetime:
        text_size: x1
        format:
          dateStyle: short
          timeStyle: short
          hour12: true
    - kubernetes:
        cluster:
          show: true
          cpu: true
          memory: true
          showLabel: true
          label: "vriska"
        nodes:
          show: true
          cpu: true
          memory: true
          showLabel: true
  kubernetes:
    mode: cluster
  docker:
  settings:
    quicklaunch:
      searchDescriptions: true
      hideInternetSearch: true

env:
  - name: TZ
    value: "America/Chicago"
  - name: HOMEPAGE_ALLOWED_HOSTS
    value: homepage.localdomain

persistence:
  logs:
    enabled: true
    type: emptyDir
    mountPath: /app/config/logs
