---
image:
  repository: ghcr.io/gethomepage/homepage
  tag: v1.2.0@sha256:5e6bcbb595c4e857540577135e0f8b3ffc2e97c23d6e0ddc7df183de5bfdd442

enableRbac: true

serviceAccount:
  create: true

service:
  main:
    annotations:
      external-dns.alpha.kubernetes.io/hostname: homepage.localdomain
    type: LoadBalancer
    ports:
      http:
        port: 80
        targetPort: 3000

env:
  - name: TZ
    value: "America/Chicago"
  - name: HOMEPAGE_ALLOWED_HOSTS
    value: homepage.localdomain

envFrom:
  - secretRef:
      name: autobrr-apikey
  - secretRef:
      name: lidarr-apikey
  - secretRef:
      name: overseerr-apikey
  - secretRef:
      name: prowlarr-apikey
  - secretRef:
      name: radarr-apikey
  - secretRef:
      name: readarr-apikey
  - secretRef:
      name: sonarr-apikey
  - secretRef:
      name: unifi-credentials

persistence:
  logs:
    enabled: true
    type: emptyDir
    mountPath: /app/config/logs

controller:
  strategy: RollingUpdate
  rollingUpdate:
    maxSurge: 25%
    maxUnavailable: 25%

config:
  bookmarks: []
  services:
  servicesString: |
    - Home:
        - UniFi Controller:
            icon: unifi.svg
            href: https://unifi.ui.com/consoles/bb5782ea-0cd7-4a31-b4e0-5566c6a25a07
            description: Dream Machine Pro
            widget:
              type: unifi
              url: https://192.168.0.1
              username: {{HOMEPAGE_VAR_UNIFI_USER}}
              password: {{HOMEPAGE_VAR_UNIFI_PASS}}
    - k8s:
        - ArgoCD:
            icon: argo-cd.svg
            href: https://argocd.mcmahan.io
            widget:
              type: argocd
              url: http://argocd-server.argocd.svc
              key: {{HOMEPAGE_VAR_ARGOCD_APIKEY}}
    - PVR:
        - Overseerr:
            icon: overseerr.svg
            href: https://overseerr.mcmahan.io
            namespace: overseerr
            app: overseerr
            widget:
              type: overseerr
              url: http://overseerr.overseerr.svc
              key: {{HOMEPAGE_VAR_OVERSEERR_APIKEY}}
        - Radarr:
            icon: radarr.svg
            href: http://radarr.localdomain
            namespace: radarr
            app: radarr
            widget:
              type: radarr
              url: http://radarr-web.radarr.svc
              key: {{HOMEPAGE_VAR_RADARR_APIKEY}}
        - Sonarr:
            icon: sonarr.svg
            href: http://sonarr.localdomain
            namespace: sonarr
            app: sonarr
            widget:
              type: sonarr
              url: http://sonarr-web.sonarr.svc
              key: {{HOMEPAGE_VAR_SONARR_APIKEY}}
        - Lidarr:
            icon: lidarr.svg
            href: http://lidarr.localdomain
            namespace: lidarr
            app: lidarr
            widget:
              type: lidarr
              url: http://lidarr-web.lidarr.svc
              key: {{HOMEPAGE_VAR_LIDARR_APIKEY}}
        - Readarr:
            icon: readarr.svg
            href: http://readarr.localdomain
            namespace: readarr
            app: readarr
            widget:
              type: readarr
              url: http://readarr-web.readarr.svc
              key: {{HOMEPAGE_VAR_READARR_APIKEY}}
        - Prowlarr:
            icon: prowlarr.svg
            href: http://prowlarr.localdomain
            namespace: prowlarr
            app: prowlarr
            widget:
              type: prowlarr
              url: http://prowlarr-web.prowlarr.svc
              key: {{HOMEPAGE_VAR_PROWLARR_APIKEY}}
        - Autobrr:
            icon: autobrr.svg
            href: http://autobrr.localdomain
            namespace: autobrr
            app: autobrr
            widget:
              type: autobrr
              url: http://autobrr.autobrr.svc
              key: {{HOMEPAGE_VAR_AUTOBRR_APIKEY}}
  widgets:
    - datetime:
        text_size: x1
        format:
          dateStyle: short
          timeStyle: short
          hour12: true
    - kubernetes:
        cluster:
          show: true
          cpu: true
          memory: true
          showLabel: true
          label: "vriska"
        nodes:
          show: true
          cpu: true
          memory: true
          showLabel: true
  kubernetes:
    mode: cluster
  docker:
  settings:
    quicklaunch:
      searchDescriptions: true
      hideInternetSearch: true
