---
image:
  repository: ghcr.io/gethomepage/homepage
  tag: v1.4.4@sha256:cd8da3c81ede2a072510930defdcf44c7a0473f72a6d5216beea3b13b3093afe

enableRbac: true

serviceAccount:
  create: true

service:
  main:
    type: LoadBalancer
    ports:
      http:
        port: 80
        targetPort: 3000

env:
  - name: TZ
    value: "America/Chicago"
  - name: HOMEPAGE_ALLOWED_HOSTS
    value: homepage.mcmahan.io

envFrom:
  - secretRef:
      name: argocd-apikey
  - secretRef:
      name: autobrr-apikey
  - secretRef:
      name: calibre-web-credentials
  - secretRef:
      name: lidarr-apikey
  - secretRef:
      name: octoprint-apikey
  - secretRef:
      name: openweather-apikey
  - secretRef:
      name: overseerr-apikey
  - secretRef:
      name: plex-apikey
  - secretRef:
      name: prowlarr-apikey
  - secretRef:
      name: qbittorrent-credentials
  - secretRef:
      name: radarr-apikey
  - secretRef:
      name: readarr-apikey
  - secretRef:
      name: sonarr-apikey
  - secretRef:
      name: unifi-credentials

persistence:
  logs:
    enabled: true
    type: emptyDir
    mountPath: /app/config/logs

controller:
  strategy: RollingUpdate
  rollingUpdate:
    maxSurge: 25%
    maxUnavailable: 25%

config:
  bookmarks:
  bookmarksString: |
    - Development:
        - GitHub:
            - abbr: GH
              icon: github.svg
              href: https://github.com/
  services:
  servicesString: |
    - Apps:
        - Kasm Workspaces:
            icon: kasm-workspaces.svg
            href: https://kasm.mcmahan.io
        - Blinko:
            icon: https://raw.githubusercontent.com/blinkospace/blinko/refs/heads/main/app/public/logo.svg
            href: https://blinko.mcmahan.io
        - Homebox:
            icon: homebox.svg
            href: https://homebox.mcmahan.io
        - Mealie:
            icon: mealie.svg
            href: https://mealie.mcmahan.io
        - OctoPrint:
            icon: octoprint.svg
            href: http://octopi.mcmahan.io
            widget:
              type: octoprint
              url: http://octopi.mcmahan.io
              key: {{HOMEPAGE_VAR_OCTOPRINT_APIKEY}}
    - Media:
        - Left:
            - Plex:
                icon: plex.svg
                href: https://plex.mcmahan.io
                widget:
                  type: plex
                  url: http://plex.plex.svc:32400
                  key: {{HOMEPAGE_VAR_PLEX_APIKEY}}
            - Calibre Web:
                icon: calibre-web.svg
                href: https://calibre-web.mcmahan.io
                widget:
                  type: calibreweb
                  url: http://calibre-web.calibre.svc
                  username: {{HOMEPAGE_VAR_CALIBRE_WEB_USER}}
                  password: {{HOMEPAGE_VAR_CALIBRE_WEB_PASS}}
            - Calibre:
                icon: calibre.svg
                href: https://calibre.mcmahan.io
        - Middle:
            - Overseerr:
                icon: overseerr.svg
                href: https://overseerr.mcmahan.io
                namespace: overseerr
                app: overseerr
                widget:
                  type: overseerr
                  url: http://overseerr.overseerr.svc
                  key: {{HOMEPAGE_VAR_OVERSEERR_APIKEY}}
            - Prowlarr:
                icon: prowlarr.svg
                href: https://prowlarr.mcmahan.io
                namespace: prowlarr
                app: prowlarr
                widget:
                  type: prowlarr
                  url: http://prowlarr-web.prowlarr.svc
                  key: {{HOMEPAGE_VAR_PROWLARR_APIKEY}}
            - Radarr:
                icon: radarr.svg
                href: https://radarr.mcmahan.io
                namespace: radarr
                app: radarr
                widget:
                  type: radarr
                  url: http://radarr-web.radarr.svc
                  key: {{HOMEPAGE_VAR_RADARR_APIKEY}}
            - Sonarr:
                icon: sonarr.svg
                href: https://sonarr.mcmahan.io
                namespace: sonarr
                app: sonarr
                widget:
                  type: sonarr
                  url: http://sonarr-web.sonarr.svc
                  key: {{HOMEPAGE_VAR_SONARR_APIKEY}}
        - Right:
            - qBittorrent:
                icon: qbittorrent.svg
                href: https://qbittorrent.mcmahan.io
                widget:
                  type: qbittorrent
                  url: http://qbittorrent-web.qbittorrent.svc
                  username: {{HOMEPAGE_VAR_QBITTORRENT_USER}}
                  password: {{HOMEPAGE_VAR_QBITTORRENT_PASS}}
            - Autobrr:
                icon: autobrr.svg
                href: https://autobrr.mcmahan.io
                namespace: autobrr
                app: autobrr
                widget:
                  type: autobrr
                  url: http://autobrr.autobrr.svc
                  key: {{HOMEPAGE_VAR_AUTOBRR_APIKEY}}
            - Lidarr:
                icon: lidarr.svg
                href: https://lidarr.mcmahan.io
                namespace: lidarr
                app: lidarr
                widget:
                  type: lidarr
                  url: http://lidarr-web.lidarr.svc
                  key: {{HOMEPAGE_VAR_LIDARR_APIKEY}}
            - Readarr:
                icon: readarr.svg
                href: https://readarr.mcmahan.io
                namespace: readarr
                app: readarr
                widget:
                  type: readarr
                  url: http://readarr-web.readarr.svc
                  key: {{HOMEPAGE_VAR_READARR_APIKEY}}
    - Homelab:
        - Left:
            - Remote Access:
                - PiKVM:
                    icon: pikvm.svg
                    href: http://pikvm
            - Monitoring:
                - Prometheus:
                    icon: prometheus.svg
                    href: https://prometheus.mcmahan.io
                - Grafana:
                    icon: grafana.svg
                    href: https://grafana.mcmahan.io
        - Middle:
            - Networking:
                - UniFi Controller:
                    icon: unifi.svg
                    href: https://unifi.ui.com/consoles/bb5782ea-0cd7-4a31-b4e0-5566c6a25a07
                    description: Dream Machine Pro
                    widget:
                      type: unifi
                      url: https://192.168.0.1
                      username: {{HOMEPAGE_VAR_UNIFI_USER}}
                      password: {{HOMEPAGE_VAR_UNIFI_PASS}}
            - Storage:
                - new-peepums:
                    icon: synology.svg
                    href: http://new-peepums.mcmahan.io:5000
        - Right:
            - k8s:
                - Sidero Omni:
                    icon: talos.svg
                    href: https://mcmahan.omni.siderolabs.io/omni
                - ArgoCD:
                    icon: argo-cd.svg
                    href: https://argocd.mcmahan.io
                    widget:
                      type: argocd
                      url: http://argocd-server.argocd.svc
                      key: {{HOMEPAGE_VAR_ARGOCD_APIKEY}}
                - Hubble UI:
                    icon: cilium.svg
                    href: https://hubble.mcmahan.io
            - Proxmox:
                - Proxmox VE:
                    icon: proxmox.svg
                    href: http://tom.mcmahan.io:8006
                - Proxmox Backup Server:
                    icon: proxmox.svg
                    href: http://pbs.mcmahan.io:8007
  widgets:
  widgetsString: |
    - datetime:
        text_size: x1
        format:
          dateStyle: short
          timeStyle: short
          hour12: true
    - openweathermap:
        label: Anamosa
        latitude: 42.093916
        longitude: -91.249325
        units: imperial
        provider: openweathermap
        apiKey: {{HOMEPAGE_VAR_OPENWEATHER_APIKEY}}
        cache: 5
        format:
          maximumFractionDigits: 1
    - kubernetes:
        cluster:
          show: true
          cpu: true
          memory: true
          showLabel: true
          label: "vriska"
        nodes:
          show: true
          cpu: true
          memory: true
          showLabel: true
  kubernetes:
    mode: cluster
  docker:
  settings:
  settingsString: |
    headerStyle: boxed
    statusStyle: "dot"
    quicklaunch:
      searchDescriptions: true
      hideInternetSearch: true
    layout:
      Apps:
        style: row
        columns: 3
      Media:
        style: row
        columns: 3
        Left:
          header: false
        Middle:
          header: false
        Right:
          header: false
      Homelab:
        style: row
        columns: 3
        Left:
          header: false
        Middle:
          header: false
        Right:
          header: false
