---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - config.yaml

helmCharts:
  - name: app-template
    repo: https://bjw-s.github.io/helm-charts
    version: 3.7.2
    releaseName: ddns-updater
    namespace: ddns
    valuesFile: values.yaml
