---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/library/common/values.schema.json
controllers:
  ddns-updater:
    containers:
      app:
        image:
          repository: ghcr.io/qdm12/ddns-updater
          tag: v2.9.0
          pullPolicy: IfNotPresent
        envFrom:
          - secretRef:
              name: ddns-config

service:
  web:
    enabled: true
    controller: ddns-updater
    type: LoadBalancer
    ports:
      http:
        port: 80
        targetPort: 8000

route:
  ddns-updater:
    hostnames: ["ddns.mcmahan.io"]
    parentRefs:
      - name: local
        namespace: traefik
        sectionName: websecure
    rules:
      - backendRefs:
          - identifier: web
            port: 80
