---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - name: postgres-operator
    repo: https://opensource.zalando.com/postgres-operator/charts/postgres-operator
    version: v1.14.0
    releaseName: postgres-operator
    namespace: postgres
  - name: postgres-operator-ui
    repo: https://opensource.zalando.com/postgres-operator/charts/postgres-operator-ui
    version: v1.14.0
    releaseName: postgres-operator-ui
    namespace: postgres
    valuesInline:
      type: LoadBalancer
      annotations:
        external-dns.alpha.kubernetes.io/hostname: postgres.localdomain
