---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: sonarr-apikey
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: default
  target:
    creationPolicy: Owner
  data:
    - secretKey: SONARR__API_KEY
      remoteRef:
        key: sonarr
        property: apikey
    - secretKey: APIKEY
      remoteRef:
        key: sonarr
        property: apikey
