---
pipelines:
  enabled: false

ollama:
  enabled: false

ollamaUrlsFromExtraEnv: true

extraEnvVars:
  - name: WEBUI_URL
    value: "https://ai.mcmahan.io"
  - name: ENABLE_PERSISTENT_CONFIG
    value: "false"
  - name: CORS_ENABLE
    value: "true"
  - name: CORS_ALLOW_ORIGIN
    value: "https://ai.mcmahan.io;http://open-webui.open-webui.svc.cluster.local"
  # features
  - name: ENABLE_OLLAMA_API
    value: "true"
  - name: OLLAMA_BASE_URLS
    value: "http://ollama.ollama.svc.cluster.local:11434"
  - name: ENABLE_OPENAI_API
    value: "false"
  # search
  - name: ENABLE_WEB_SEARCH
    value: "true"
  - name: WEB_SEARCH_ENGINE
    value: "searxng"
  - name: SEARXNG_QUERY_URL
    value: "http://searxng.searxng.svc.cluster.local:8080/search?q=<query>"
  - name: USER_AGENT
    value: "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36"

route:
  enabled: true
  hostnames: ["ai.mcmahan.io"]
  parentRefs:
    - name: local
      namespace: traefik
      sectionName: websecure

sso:
  enabled: true
  mergeAccountsByEmail: true
  oidc:
    enabled: true
    providerName: "authentik"
    providerUrl: "https://auth.mcmahan.io/application/o/open-webui/.well-known/openid-configuration"
    clientExistingSecret: open-webui-oidc
    clientIdExistingSecretKey: OAUTH_CLIENT_ID
    clientExistingSecretKey: OAUTH_CLIENT_SECRET
