---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - spidermom.yaml
  - storageclass.yaml
  - volumesnapshotclass.yaml

helmCharts:
  - name: miroir
    repo: oci://ghcr.io/home-operations/charts
    version: 0.12.2
    releaseName: miroir
    namespace: miroir-system
    valuesFile: values.yaml
