apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: duckdns-credentials
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: default
  target:
    creationPolicy: Owner
  dataFrom:
  - extract:
      key: duckdns
      property: token
