---
ingressRoute:
  dashboard:
    enabled: true
    insecure: true

api:
  dashboard: true
  insecure: true

ingressClass:
  enabled: true
  isDefaultClass: true

service:
  type: LoadBalancer
  spec:
    loadBalancerIP: "192.168.8.80"

ports:
  web:
    redirections:
      entryPoint:
        to: websecure
