---
# yaml-language-server: $schema=https://raw.githubusercontent.com/traefik/traefik-helm-chart/master/traefik/values.schema.json
ingressRoute:
  dashboard:
    enabled: true
    insecure: true

api:
  dashboard: true
  insecure: true

ingressClass:
  enabled: true
  isDefaultClass: true

service:
  type: LoadBalancer
  spec:
    loadBalancerIP: "192.168.8.80"
  additionalServices:
    local:
      type: LoadBalancer
      spec:
        loadBalancerIP: "192.168.8.81"
      labels:
        traefik-service-label: local

ports:
  local:
    port: 9000
    expose:
      default: false
      local: true
    exposedPort: 80
    targetPort: web
    redirections:
      entryPoint:
        to: localsecure
        scheme: https
  localsecure:
    port: 9443
    expose:
      default: false
      local: true
    exposedPort: 443
    targetPort: websecure
    tls:
      enabled: true
  web:
    redirections:
      entryPoint:
        to: websecure
        scheme: https

metrics:
  prometheus:
    serviceMonitor:
      enabled: true
