---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/library/common/values.schema.json
controllers:
  flaresolverr:
    containers:
      app:
        image:
          repository: 21hsmw/flaresolverr
          tag: nodriver@sha256:dca8cda5852b04e6142752fc044c9845eb536353ea6f8b7bb58b4ff9419538fa
          pullPolicy: IfNotPresent
        env:
          TZ: "America/Chicago"
          PROMETHEUS_ENABLED: "true"

service:
  web:
    enabled: true
    controller: flaresolverr
    ports:
      http:
        port: 80
        targetPort: 8191
  metrics:
    controller: flaresolverr
    ports:
      metrics:
        port: 8192
