---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/library/common/values.schema.json
controllers:
  flaresolverr:
    containers:
      app:
        image:
          repository: 21hsmw/flaresolverr
          tag: nodriver@sha256:3d99be35f845750adba3b9aa23844b7f585eeac6b1b45157bf14aaa8f7d16e20
          pullPolicy: IfNotPresent
        env:
          TZ: "America/Chicago"
          PROMETHEUS_ENABLED: "true"

service:
  web:
    enabled: true
    controller: flaresolverr
    ports:
      http:
        port: 80
        targetPort: 8191
  metrics:
    controller: flaresolverr
    ports:
      metrics:
        port: 8192
