---
controllers:
  main:
    containers:
      main:
        image:
          repository: ghcr.io/flaresolverr/flaresolverr
          tag: v3.3.13
          pullPolicy: IfNotPresent
        env:
          TZ: "America/Chicago"
