---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/library/common/values.schema.json
controllers:
  autobrr:
    containers:
      app:
        image:
          repository: ghcr.io/autobrr/autobrr
          tag: v1.62.0
          pullPolicy: IfNotPresent
        env:
          TZ: "America/Chicago"
          AUTOBRR__CHECK_FOR_UPDATES: "false"
          AUTOBRR__HOST: 0.0.0.0
          AUTOBRR__PORT: &port 80
          AUTOBRR__LOG_LEVEL: INFO

service:
  web:
    enabled: true
    controller: autobrr
    type: LoadBalancer
    ports:
      http:
        port: *port

route:
  autobrr:
    hostnames: ["autobrr.mcmahan.io"]
    parentRefs:
      - name: local
        namespace: traefik
        sectionName: websecure
    rules:
      - backendRefs:
          - identifier: web
            port: *port

persistence:
  config:
    enabled: true
    existingClaim: autobrr-config
    advancedMounts:
      autobrr:
        app:
          - path: /config
