---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: authentik-secret-key
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: default
  target:
    creationPolicy: Owner
  dataFrom:
    - extract:
        conversionStrategy: Default
        decodingStrategy: None
        key: authentik
        metadataPolicy: None
        property: secretKey
