---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: authentik-secret-key
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: default
  target:
    creationPolicy: Owner
  dataFrom:
    - extract:
        conversionStrategy: Default
        decodingStrategy: None
        key: authentik
        metadataPolicy: None
        property: secretKey
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: authentik-smtp
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: default
  target:
    creationPolicy: Owner
  data:
    - secretKey: AUTHENTIK_EMAIL__HOST
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
        key: authentik
        property: smtp.host
    - secretKey: AUTHENTIK_EMAIL__FROM
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
        key: authentik
        property: smtp.from
    - secretKey: AUTHENTIK_EMAIL__USERNAME
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
        key: authentik
        property: smtp.username
    - secretKey: AUTHENTIK_EMAIL__PASSWORD
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
        key: authentik
        property: smtp.password
