---
global:
  env:
    - name: AUTHENTIK_SECRET_KEY
      valueFrom:
        secretKeyRef:
          name: authentik-secret-key
          key: secretKey
    - name: AUTHENTIK_POSTGRESQL__HOST
      valueFrom:
        secretKeyRef:
          name: authentik-cluster-app
          key: host
    - name: AUTHENTIK_POSTGRESQL__NAME
      valueFrom:
        secretKeyRef:
          name: authentik-cluster-app
          key: dbname
    - name: AUTHENTIK_POSTGRESQL__USER
      valueFrom:
        secretKeyRef:
          name: authentik-cluster-app
          key: username
    - name: AUTHENTIK_POSTGRESQL__PASSWORD
      valueFrom:
        secretKeyRef:
          name: authentik-cluster-app
          key: password
  envFrom:
    - secretRef:
        name: authentik-smtp

server:
  route:
    main:
      enabled: true
      hostnames:
        - auth.mcmahan.io
      parentRefs:
        - name: remote
          namespace: traefik
          sectionName: websecure

  metrics:
    enabled: true
  serviceMonitor:
    enabled: true

authentik:
  email:
    port: 587
    use_tls: true
    use_ssl: false

prometheus:
  rules:
    enabled: true
