---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/gateway.networking.k8s.io/gateway_v1.json
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: local
  annotations:
    external-dns.alpha.kubernetes.io/target: local.mcmahan.io
spec:
  gatewayClassName: traefik
  infrastructure:
    annotations:
      external-dns.alpha.kubernetes.io/hostname: local.mcmahan.io
  listeners:
    - name: http
      protocol: HTTP
      port: 80
      hostname: "*.mcmahan.io"
      allowedRoutes:
        namespaces:
          from: Same
    - name: https
      protocol: HTTPS
      port: 443
      hostname: "*.mcmahan.io"
      allowedRoutes:
        namespaces:
          from: All
