---
apiVersion: config.terraform.padok.cloud/v1alpha1
kind: TerraformRepository
metadata:
  name: cloudflare
  namespace: burrito-project-default
spec:
  repository:
    url: git@github.com:jdmcmahan/cloudflare-tf.git
    secretName: github-token
  terraform:
    enabled: true
---
apiVersion: config.terraform.padok.cloud/v1alpha1
kind: TerraformLayer
metadata:
  name: cloudflare-root
  namespace: burrito-project-default
spec:
  branch: "main"
  repository:
    name: cloudflare
    namespace: burrito-project-default
