apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
- name: external-secrets
  repo: https://charts.external-secrets.io
  version: 0.9.1
  releaseName: external-secrets
  namespace: external-secrets
  valuesInline:
    serviceMonitor.enabled: "true"
    webhook.serviceMonitor.enabled: "true"
    certController.serviceMonitor.enabled: "true"
