---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: blinko-cluster
spec:
  instances: 3

  storage:
    storageClass: ceph-block
    size: 1Gi

  monitoring:
    enablePodMonitor: true