---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/library/common/values.schema.json
controllers:
  blinko:
    containers:
      app:
        image:
          repository: blinkospace/blinko
          tag: 0.52.3
          pullPolicy: IfNotPresent
        env:
          TZ: "America/Chicago"
          NODE_ENV: production
          NEXTAUTH_URL: https://blinko.mcmahan.io
          NEXT_PUBLIC_BASE_URL: https://blinko.mcmahan.io
          # DATABASE_URL: postgresql://postgres:mysecretpassword@postgres:5432/postgres
        envFrom:
          - secretRef:
              name: blinko-auth-secret
        probes:
          liveness: &probes
            enabled: true
            custom: true
            spec:
              httpGet:
                port: 1111
              initialDelaySeconds: 30
              periodSeconds: 30
              timeoutSeconds: 10
              failureThreshold: 5
          readiness: *probes
          startup:
            enabled: true
            spec:
              failureThreshold: 30
              periodSeconds: 30

service:
  web:
    enabled: true
    controller: blinko
    annotations:
      external-dns.alpha.kubernetes.io/hostname: blinko.localdomain
    type: LoadBalancer
    ports:
      http:
        port: 80
        targetPort: 1111

ingress:
  blinko:
    enabled: true
    annotations:
      cert-manager.io/cluster-issuer: cloudflare
      traefik.ingress.kubernetes.io/router.entrypoints: websecure
      traefik.ingress.kubernetes.io/router.tls: "true"
    hosts:
    - host: blinko.mcmahan.io
      paths:
      - path: /
        pathType: Prefix
        service:
          identifier: web
          port: http
    tls:
    - secretName: 'blinko-cert'
      hosts:
      - blinko.mcmahan.io
