---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - "namespace.yaml"
  - "https://github.com/kubernetes-sigs/node-feature-discovery/deployment/base/nfd-crds?ref=v0.18.1"
  - "https://github.com/intel/intel-device-plugins-for-kubernetes/deployments/operator/crd?ref=v0.34.0"

helmCharts:
  - name: node-feature-discovery
    repo: https://kubernetes-sigs.github.io/node-feature-discovery/charts
    version: 0.18.1
    releaseName: node-feature-discovery
    namespace: intel
  - name: intel-device-plugins-operator
    repo: https://intel.github.io/helm-charts
    version: 0.34.0
    releaseName: intel-device-plugins-operator
    namespace: intel
  - name: intel-device-plugins-gpu
    repo: https://intel.github.io/helm-charts
    version: 0.34.0
    releaseName: intel-device-plugins-gpu
    namespace: intel
    valuesInline:
      name: gpudeviceplugin-default
      sharedDevNum: 2
      nodeFeatureRule: true
      tolerations: []

patches:
  - patch: |-
      apiVersion: deviceplugin.intel.com/v1
      kind: GpuDevicePlugin
      metadata:
        name: gpudeviceplugin-default
      spec:
        resourceManager: null
    target:
      kind: GpuDevicePlugin
      name: "gpudeviceplugin-default"
