---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: onepassword-connect-token-tf
  namespace: burrito-project-default
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: default
  target:
    creationPolicy: Owner
  data:
    - secretKey: token
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
        key: 1password-connect-token-tf
        property: credential
---
apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: tf
  namespace: burrito-project-default
spec:
  provider:
    onepassword:
      connectHost: http://onepassword-connect.onepassword.svc.cluster.local:8080
      vaults:
        tf: 1
      auth:
        secretRef:
          connectTokenSecretRef:
            name: onepassword-connect-token-tf
            namespace: burrito-project-default
            key: token
