---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: external-dns

resources:
  - unifi-credentials.yaml
  - cloudflare-token.yaml

helmCharts:
  - name: external-dns
    repo: https://kubernetes-sigs.github.io/external-dns/
    version: 1.19.0
    releaseName: external-dns-unifi
    namespace: external-dns
    valuesFile: values-unifi.yaml
  - name: external-dns
    repo: https://kubernetes-sigs.github.io/external-dns/
    version: 1.19.0
    releaseName: external-dns-cloudflare
    namespace: external-dns
    valuesFile: values-cloudflare.yaml
