---
provider:
  name: webhook
  webhook:
    image:
      repository: ghcr.io/kashalls/external-dns-unifi-webhook
      tag: v0.5.2@sha256:e1eef62e8d9f1966def6f2efc89ff42bcaba1060b0c2957d9cab57a11c900d5c
    env:
      - name: UNIFI_HOST
        value: https://192.168.0.1
      - name: UNIFI_USER
        valueFrom:
          secretKeyRef:
            name: unifi-credentials
            key: UNIFI_USER
      - name: UNIFI_PASS
        valueFrom:
          secretKeyRef:
            name: unifi-credentials
            key: UNIFI_PASS
    livenessProbe:
      httpGet:
        path: /healthz
        port: http-webhook
      initialDelaySeconds: 10
      timeoutSeconds: 5
    readinessProbe:
      httpGet:
        path: /readyz
        port: http-webhook
      initialDelaySeconds: 10
      timeoutSeconds: 5
extraArgs:
  - --ignore-ingress-tls-spec
policy: sync
sources: ["ingress", "service"]
txtOwnerId: vriska
txtPrefix: k8s.vriska.
domainFilters: ["mcmahan.io", "localdomain"]
serviceMonitor:
  enabled: true
