apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - "namespace.yaml"
  - "https://github.com/intel/intel-device-plugins-for-kubernetes/deployments/operator/crd?ref=v0.28.0"
  - "https://github.com/intel/intel-device-plugins-for-kubernetes/deployments/nfd/overlays/node-feature-rules?ref=v0.28.0"

helmCharts:
  - name: node-feature-discovery
    repo: https://kubernetes-sigs.github.io/node-feature-discovery/charts
    version: 0.14.3
    releaseName: node-feature-discovery
    namespace: intel
  - name: intel-device-plugins-operator
    repo: https://intel.github.io/helm-charts
    version: 0.28.0
    releaseName: intel-device-plugins-operator
    namespace: intel
  - name: intel-device-plugins-gpu
    repo: https://intel.github.io/helm-charts
    version: 0.28.0
    releaseName: intel-device-plugins-gpu
    namespace: intel

patches:
- patch: |-
    apiVersion: v1
    kind: GpuDevicePlugin
    metadata:
      name: gpudeviceplugin-sample
    spec:
      resourceManager: false
  target:
    kind: GpuDevicePlugin
    name: "gpudeviceplugin-sample"