---
metrics:
  enabled: true

prometheus:
  serviceMonitor:
    enabled: true
  inferencePodMonitor:
    enabled: true

grafana:
  dashboards:
    enabled: false
    operator:
      enabled: false

modelCache:
  enabled: true
  size: 120Gi
  storageClass: ceph-block
