---
# yaml-language-server: $schema=https://raw.githubusercontent.com/defilantech/LLMKube/main/charts/llmkube/values.schema.json
metrics:
  enabled: true
  secure: false

prometheus:
  serviceMonitor:
    enabled: true
  inferencePodMonitor:
    enabled: true
  routerPodMonitor:
    enabled: true

grafana:
  dashboards:
    enabled: true
    additionalLabels:
      grafana_dashboard: "1"
    operator:
      enabled: false

modelCache:
  enabled: true
  size: 120Gi
  storageClass: miroir-local
