---
metrics:
  enabled: true

prometheus:
  serviceMonitor:
    enabled: true
  inferencePodMonitor:
    enabled: true

grafana:
  dashboards:
    enabled: true
    additionalLabels:
      grafana_dashboard: "1"
    operator:
      enabled: false

modelCache:
  enabled: true
  mode: perService
  size: 120Gi
  storageClass: ceph-block
