---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: ddclient-conf-cloudflare
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: default
  target:
    creationPolicy: Owner
  dataFrom:
    - extract:
        conversionStrategy: Default
        decodingStrategy: None
        key: ddclient-cloudflare
        metadataPolicy: None
        property: ddclient.conf
