---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ddclient
  labels:
    app: ddclient
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  replicas: 1
  selector:
    matchLabels:
      app: ddclient
  template:
    metadata:
      labels:
        app: ddclient
    spec:
      volumes:
        - name: ddclient-config
          secret:
            secretName: ddclient-conf-cloudflare
      containers:
        - name: ddclient
          image: linuxserver/ddclient:4.0.0
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - mountPath: /defaults/ddclient.conf
              subPath: ddclient.conf
              name: ddclient-config
          resources:
            requests:
              cpu: 10m
              memory: 64Mi
            limits:
              cpu: 50m
              memory: 128Mi
