---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/monitoring.coreos.com/alertmanagerconfig_v1alpha1.json
apiVersion: monitoring.coreos.com/v1alpha1
kind: AlertmanagerConfig
metadata:
  name: alertmanager
spec:
  route:
    receiver: "null"
    continue: false
    groupBy: ["alertname", "job"]
    groupWait: 1m
    groupInterval: 10m
    repeatInterval: 12h
    routes:
      - receiver: "null"
        continue: false
        matchers:
          - name: alertname
            value: Watchdog
            matchType: =
      - receiver: pushover
        continue: false
        matchers:
          - name: severity
            value: critical
            matchType: =
  inhibitRules:
    - equal: ["namespace", "alertname"]
      sourceMatch:
        - name: severity
          value: critical
          matchType: =
      targetMatch:
        - name: severity
          value: warning|info
          matchType: =~
    - equal: ["namespace", "alertname"]
      sourceMatch:
        - name: severity
          value: warning
          matchType: =
      targetMatch:
        - name: severity
          value: info
          matchType: =
    - equal: ["namespace"]
      sourceMatch:
        - name: alertname
          value: InfoInhibitor
          matchType: =
      targetMatch:
        - name: severity
          value: info
          matchType: =
    - targetMatch:
        - name: alertname
          value: InfoInhibitor
          matchType: =
  receivers:
    - name: "null"
    - name: pushover
      pushoverConfigs:
        - sendResolved: true
          urlTitle: View in Alertmanager
          sound: gamelan
          ttl: 86400s
          userKey:
            name: pushover-token
            key: userKey
          token:
            name: pushover-token
            key: token
