---
config:
  settings:
    server:
      base_url: "https://search.mcmahan.io"
    search:
      autocomplete: duckduckgo
      favicon_resolver: duckduckgo
      languages:
        - all
        - en
        - en-US
      formats:
        - html
        - json

gateway:
  enabled: true
  hostnames: [ "search.mcmahan.io" ]
  parentRefs:
    - name: local
      namespace: traefik
      sectionName: websecure
