---
extraEnv:
  - name: TZ
    value: "America/Chicago"

config:
  persistence:
    existingClaim: overseerr-config

route:
  main:
    enabled: true
    hostnames: ["seerr.mcmahan.io"]
    parentRefs:
      - name: remote
        namespace: traefik
        sectionName: websecure
