---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: lancache

resources:
  - steam-account.yaml

helmCharts:
  - name: app-template
    repo: https://bjw-s.github.io/helm-charts
    version: 3.4.0
    releaseName: lancache
    namespace: lancache
    valuesFile: values.yaml
