---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/library/common/values.schema.json
controllers:
  lancache:
    containers:
      app:
        image:
          repository: lancachenet/monolithic
          tag: latest@sha256:07d659d66bbaac9ca99712ab37d56419dde974bac1847434ea47489290f25a9a
          pullPolicy: IfNotPresent
        env:
          TZ: "America/Chicago"
          CACHE_DISK_SIZE: 4000g
          CACHE_INDEX_SIZE: 1000m
      dns:
        image:
          repository: lancachenet/lancache-dns
          tag: latest@sha256:710d3ebc3f1a754b9587168056d1213f8a75cb1b84d65262260b671d92eba86b
          pullPolicy: IfNotPresent
        env:
          TZ: "America/Chicago"
          USE_GENERIC_CACHE: "true"
          LANCACHE_IP: &ip "192.168.8.54"
          UPSTREAM_DNS: "192.168.0.1"
  steam-prefill:
    type: cronjob
    cronjob:
      schedule: "@daily"
      successfulJobsHistory: 1
      failedJobsHistory: 1
    pod:
      dnsPolicy: None
      dnsConfig:
        nameservers:
        - *ip
    containers:
      app:
        image:
          repository: tpill90/steam-lancache-prefill
          tag: v2.8.1
          pullPolicy: IfNotPresent
        args:
          - prefill
          - "--all"
          - "--verbose"
          - "--no-ansi"
          - "--os"
          - "windows"
          - "--os"
          - "macos"
          - "--os"
          - "linux"
        env:
          TZ: "America/Chicago"

service:
  main:
    enabled: true
    controller: lancache
    type: LoadBalancer
    loadBalancerIP: *ip
    annotations:
      metallb.universe.tf/allow-shared-ip: lancache-svc
    ports:
      http:
        port: 80
      https:
        port: 443
  dns:
    enabled: true
    controller: lancache
    type: LoadBalancer
    loadBalancerIP: *ip
    annotations:
      metallb.universe.tf/allow-shared-ip: lancache-svc
    ports:
      dns:
        port: 53

persistence:
  cache:
    enabled: true
    type: nfs
    server: new-peepums
    path: /volume1/lancache
    advancedMounts:
      lancache:
        app:
          - path: /data/cache
  steam-prefill-config:
    enabled: true
    type: persistentVolumeClaim
    storageClass: ceph-block
    size: 10Gi
    accessMode: ReadWriteOnce
    advancedMounts:
      steam-prefill:
        app:
          - path: /Config
  steam-prefill-account:
    enabled: true
    type: secret
    name: steam-account
    advancedMounts:
      steam-prefill:
        app:
          - path: /Config/account.config
            subPath: account.config
            readOnly: true
