---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - pvc.yaml
  - postgres.yaml
  - secrets-immichframe.yaml

configMapGenerator:
  - name: immichframe-config
    files:
      - Settings.yml=./config/immichframe/Settings.yml

generatorOptions:
  disableNameSuffixHash: true

helmCharts:
  - name: immich
    repo: https://immich-app.github.io/immich-charts
    version: 0.12.0
    releaseName: immich
    namespace: immich
    valuesFile: values-immich.yaml
  - name: app-template
    repo: https://bjw-s-labs.github.io/helm-charts
    version: 5.0.1
    releaseName: immichframe
    namespace: immich
    valuesFile: values-immichframe.yaml
