---
# yaml-language-server: $schema=https://raw.githubusercontent.com/cloudnative-pg/charts/main/charts/cluster/values.schema.json
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: immich-cluster
spec:
  instances: 1

  storage:
    storageClass: ceph-block
    size: 100Gi

  imageName: ghcr.io/tensorchord/cloudnative-vectorchord:18.3-1.1.1

  monitoring:
    enablePodMonitor: true

  postgresql:
    shared_preload_libraries:
      - "vchord.so"

  bootstrap:
    initdb:
      postInitApplicationSQL:
        - CREATE EXTENSION vchord CASCADE;
        - CREATE EXTENSION earthdistance CASCADE;
