---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/library/common/values.schema.json
controllers:
  main:
    containers:
      main:
        image:
          repository: docker.io/altran1502/immich-server
          tag: v2.6.3
          pullPolicy: IfNotPresent
        env:
          TZ: "America/Chicago"
          DB_HOSTNAME:
            valueFrom:
              secretKeyRef:
                name: immich-cluster-app
                key: host
          DB_DATABASE_NAME:
            valueFrom:
              secretKeyRef:
                name: immich-cluster-app
                key: dbname
          DB_USERNAME:
            valueFrom:
              secretKeyRef:
                name: immich-cluster-app
                key: username
          DB_PASSWORD:
            valueFrom:
              secretKeyRef:
                name: immich-cluster-app
                key: password

immich:
  metrics:
    enabled: true
  persistence:
    library:
      existingClaim: immich-library

valkey:
  enabled: true

route:
  immich:
    hostnames: ["immich.mcmahan.io"]
    parentRefs:
      - name: local
        namespace: traefik
        sectionName: websecure
    rules:
      - backendRefs:
          - name: immich-server
            port: 2283
