---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/library/common/values.schema.json
controllers:
  immichframe:
    containers:
      app:
        image:
          repository: ghcr.io/immichframe/immichframe
          tag: v1.0.33.0@sha256:1680d2f63a89fa0db6e5a7c5c497bed27a47f314efe18e1f11cff1dea1910f57
          pullPolicy: IfNotPresent
        env:
          TZ: "America/Chicago"
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          capabilities:
            drop:
              - ALL

defaultPodOptions:
  securityContext:
    fsGroupChangePolicy: "OnRootMismatch"
    runAsNonRoot: true

service:
  web:
    enabled: true
    controller: immichframe
    type: LoadBalancer
    ports:
      http:
        port: 8080

route:
  immichframe:
    hostnames: ["immichframe.mcmahan.io"]
    parentRefs:
      - name: remote
        namespace: traefik
        sectionName: websecure
    rules:
      - backendRefs:
          - identifier: web
            port: 8080

persistence:
  config:
    type: secret
    name: immichframe-config
    globalMounts:
      - path: /app/Config/Settings.yml
        subPath: Settings.yml
        readOnly: true
