---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: argocd-dex
  namespace: argocd
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: default
  target:
    name: argocd-secret
    creationPolicy: Merge
    template:
      data:
        dex.authentik.clientSecret: "{{ .clientSecret }}"
  data:
    - secretKey: clientSecret
      remoteRef:
        key: argocd
        property: clientSecret
