---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd

resources:
  - namespace.yaml
  - applications.yaml

helmCharts:
  - name: argo-cd
    repo: https://argoproj.github.io/argo-helm
    version: 5.51.5
    releaseName: argocd
    namespace: argocd
    valuesInline:
      redis-ha:
        enabled: true
      params:
        server.insecure: true
      configs:
        cm:
          kustomize.buildOptions: "--enable-helm"
          resource.exclusions: |
            - apiGroups:
                - cilium.io
              kinds:
                - CiliumIdentity
              clusters:
                - "*"
      controller:
        replicas: 1
        metrics:
          enabled: true
      server:
        autoscaling:
          enabled: true
          minReplicas: 2
        metrics:
          enabled: true
        service:
          annotations:
            external-dns.alpha.kubernetes.io/hostname: argocd.localdomain
          type: LoadBalancer
        ingress:
          enabled: true
          annotations:
            traefik.ingress.kubernetes.io/router.entrypoints: websecure
            traefik.ingress.kubernetes.io/router.tls: "true"
            cert-manager.io/cluster-issuer: cloudflare
          hosts:
            - argocd.mcmahan.io
          tls:
            - secretName: argocd-cert
              hosts:
                - argocd.mcmahan.io
      repoServer:
        autoscaling:
          enabled: true
          minReplicas: 2
        metrics:
          enabled: true
      applicationSet:
        replicas: 2
        metrics:
          enabled: true
