apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd

resources:
- github.com/argoproj/argo-cd/manifests/ha/base?ref=v2.7.7
- ingress.yaml
- applications.yaml

patches:
- patch: |-
    - op: add
      path: "/data"
      value:
        server.insecure: "true"
  target:
    kind: ConfigMap
    name: "argocd-cmd-params-cm"
- patch: |-
    - op: add
      path: "/data"
      value:
        kustomize.buildOptions: "--enable-helm"
        resource.customizations.ignoreDifferences.apiextensions.k8s.io_CustomResourceDefinition: |
          jsonPointers:
          - spec/conversion/webhook/clientConfig/caBundle
        resource.exclusions: |-
          - apiGroups:
            - cilium.io
            kinds:
            - CiliumIdentity
            clusters:
            - "*"
  target:
    kind: ConfigMap
    name: "argocd-cm"
