apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd

resources:
- namespace.yaml
- https://github.com/argoproj/argo-cd/manifests/ha/base?ref=v2.7.10
- ingress.yaml
- applications.yaml

patches:
- patch: |-
    apiVersion: v1
    kind: ConfigMap
    metadata:
      name: argocd-cmd-params-cm
    data:
      server.insecure: "true"
  target:
    kind: ConfigMap
    name: "argocd-cmd-params-cm"
- patch: |-
    apiVersion: v1
    kind: ConfigMap
    metadata:
      name: argocd-cm
    data:
      kustomize.buildOptions: "--enable-helm"
      application.instanceLabelKey: "argocd.argoproj.io/instance"
      resource.customizations.ignoreDifferences.apiextensions.k8s.io_CustomResourceDefinition: |
        jsonPointers:
        - spec/conversion/webhook/clientConfig/caBundle
      resource.exclusions: |-
        - apiGroups:
          - cilium.io
          kinds:
          - CiliumIdentity
          clusters:
          - "*"
  target:
    kind: ConfigMap
    name: "argocd-cm"
- patch: |-
    apiVersion: v1
    kind: Service
    metadata:
      name: argocd-server
      annotations:
        external-dns.alpha.kubernetes.io/hostname: argocd.localdomain
    spec:
      type: LoadBalancer
  target:
    kind: Service
    name: "argocd-server"
