apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: argocd-exporter
  namespace: argocd
spec:
  endpoints:
  - port: "9001"
    scheme: http
  selector:
    matchLabels:
      app.kubernetes.io/instance: argocd
      app.kubernetes.io/name: argocd-notifications-controller-metrics
