apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: argocd-monitor
  namespace: prometheus
  labels:
    release: kube-prometheus-stack
spec:
  endpoints:
  - port: "9001"
    scheme: http
  selector:
    matchLabels:
      app.kubernetes.io/instance: argocd
      app.kubernetes.io/name: argocd-notifications-controller-metrics
