---
kind: Cluster
name: vriska
kubernetes:
  version: v1.34.1
talos:
  version: v1.11.5
features:
  enableWorkloadProxy: true
  backupConfiguration:
    interval: 24h
patches:
  - name: control-plane-workers
    inline:
      cluster:
        allowSchedulingOnControlPlanes: true
  - name: cilium-override
    file: ../patches/cilium-override.yaml
---
kind: ControlPlane
machines:
  - 4c4c4544-004a-4310-8042-b4c04f365132
  - 4c4c4544-0043-4210-8035-b4c04f365132
  - 4c4c4544-0039-4a10-8048-b9c04f305432
---
kind: Workers
name: storage
machines:
  - 4c4c4544-0052-4610-8054-b3c04f4e5932
  - 4c4c4544-0052-4e10-8054-b3c04f4e5932
  - 4c4c4544-0052-4810-8054-b3c04f4e5932
---
kind: Machine
name: 4c4c4544-004a-4310-8042-b4c04f365132
install:
  disk: /dev/nvme0n1
patches:
  - name: hostname
    inline:
      machine:
        network:
          hostname: vision-eightfold
  - name: kexec-disable
    file: ../patches/kexec-disable.yaml
  - name: gc-threshold
    file: ../patches/gc-threshold.yaml
  - name: cloudflared-quic
    file: ../patches/cloudflared-quic.yaml
systemExtensions:
  - siderolabs/intel-ucode
  - siderolabs/i915
---
kind: Machine
name: 4c4c4544-0043-4210-8035-b4c04f365132
install:
  disk: /dev/nvme0n1
patches:
  - name: hostname
    inline:
      machine:
        network:
          hostname: psychic-manipulation
  - name: kexec-disable
    file: ../patches/kexec-disable.yaml
  - name: gc-threshold
    file: ../patches/gc-threshold.yaml
  - name: cloudflared-quic
    file: ../patches/cloudflared-quic.yaml
systemExtensions:
  - siderolabs/intel-ucode
  - siderolabs/i915
---
kind: Machine
name: 4c4c4544-0039-4a10-8048-b9c04f305432
install:
  disk: /dev/nvme0n1
patches:
  - name: hostname
    inline:
      machine:
        network:
          hostname: enviable-cerulean-swill
  - name: kexec-disable
    file: ../patches/kexec-disable.yaml
  - name: gc-threshold
    file: ../patches/gc-threshold.yaml
  - name: cloudflared-quic
    file: ../patches/cloudflared-quic.yaml
systemExtensions:
  - siderolabs/intel-ucode
  - siderolabs/i915
---
kind: Machine
name: 4c4c4544-0052-4610-8054-b3c04f4e5932
install:
  disk: /dev/nvme0n1
patches:
  - name: hostname
    inline:
      machine:
        network:
          hostname: magic-8-balls
  - name: kexec-disable
    file: ../patches/kexec-disable.yaml
  - name: gc-threshold
    file: ../patches/gc-threshold.yaml
  - name: cloudflared-quic
    file: ../patches/cloudflared-quic.yaml
systemExtensions:
  - siderolabs/intel-ucode
  - siderolabs/i915
---
kind: Machine
name: 4c4c4544-0052-4e10-8054-b3c04f4e5932
install:
  disk: /dev/nvme0n1
patches:
  - name: hostname
    inline:
      machine:
        network:
          hostname: omniscient-cue-ball
  - name: kexec-disable
    file: ../patches/kexec-disable.yaml
  - name: gc-threshold
    file: ../patches/gc-threshold.yaml
  - name: cloudflared-quic
    file: ../patches/cloudflared-quic.yaml
systemExtensions:
  - siderolabs/intel-ucode
  - siderolabs/i915
---
kind: Machine
name: 4c4c4544-0052-4810-8054-b3c04f4e5932
install:
  disk: /dev/nvme0n1
patches:
  - name: hostname
    inline:
      machine:
        network:
          hostname: flourite-octet
  - name: kexec-disable
    file: ../patches/kexec-disable.yaml
  - name: gc-threshold
    file: ../patches/gc-threshold.yaml
  - name: cloudflared-quic
    file: ../patches/cloudflared-quic.yaml
systemExtensions:
  - siderolabs/intel-ucode
  - siderolabs/i915
