---
kind: Cluster
name: vriska
kubernetes:
  version: v1.36.4
talos:
  version: v1.14.0
features:
  enableWorkloadProxy: true
  backupConfiguration:
    interval: 24h
patches:
  - name: control-plane-workers
    file: patches/control-plane-workers.yaml
  - name: cilium-override
    file: patches/cilium-override.yaml
---
kind: ControlPlane
machines:
  - 4c4c4544-004a-4310-8042-b4c04f365132
  - 4c4c4544-0043-4210-8035-b4c04f365132
  - 4c4c4544-0039-4a10-8048-b9c04f305432
---
kind: Workers
name: storage
machines:
  - 4c4c4544-0052-4610-8054-b3c04f4e5932
  - 4c4c4544-0052-4e10-8054-b3c04f4e5932
  - 4c4c4544-0052-4810-8054-b3c04f4e5932
---
kind: Workers
name: ai
machines:
  - ad064900-a236-11f1-926b-11bbce7a6b00
---
kind: Machine
name: 4c4c4544-004a-4310-8042-b4c04f365132
patches:
  - name: install-disk
    inline: |
      apiVersion: v1alpha1
      kind: UnattendedInstallConfig
      provisioning:
        diskSelector:
          match: disk.dev_path == "/dev/nvme0n1"
  - name: hostname
    inline: |
      apiVersion: v1alpha1
      kind: HostnameConfig
      hostname: vision-eightfold
  - name: kexec-disable
    file: patches/kexec-disable.yaml
  - name: gc-threshold
    file: patches/gc-threshold.yaml
  - name: cloudflared-quic
    file: patches/cloudflared-quic.yaml
systemExtensions:
  - siderolabs/intel-ucode
  - siderolabs/i915
---
kind: Machine
name: 4c4c4544-0043-4210-8035-b4c04f365132
patches:
  - name: install-disk
    inline: |
      apiVersion: v1alpha1
      kind: UnattendedInstallConfig
      provisioning:
        diskSelector:
          match: disk.dev_path == "/dev/nvme0n1"
  - name: hostname
    inline: |
      apiVersion: v1alpha1
      kind: HostnameConfig
      hostname: psychic-manipulation
  - name: kexec-disable
    file: patches/kexec-disable.yaml
  - name: gc-threshold
    file: patches/gc-threshold.yaml
  - name: cloudflared-quic
    file: patches/cloudflared-quic.yaml
systemExtensions:
  - siderolabs/intel-ucode
  - siderolabs/i915
---
kind: Machine
name: 4c4c4544-0039-4a10-8048-b9c04f305432
patches:
  - name: install-disk
    inline: |
      apiVersion: v1alpha1
      kind: UnattendedInstallConfig
      provisioning:
        diskSelector:
          match: disk.dev_path == "/dev/nvme0n1"
  - name: hostname
    inline: |
      apiVersion: v1alpha1
      kind: HostnameConfig
      hostname: enviable-cerulean-swill
  - name: kexec-disable
    file: patches/kexec-disable.yaml
  - name: gc-threshold
    file: patches/gc-threshold.yaml
  - name: cloudflared-quic
    file: patches/cloudflared-quic.yaml
systemExtensions:
  - siderolabs/intel-ucode
  - siderolabs/i915
---
kind: Machine
name: 4c4c4544-0052-4610-8054-b3c04f4e5932
patches:
  - name: install-disk
    inline: |
      apiVersion: v1alpha1
      kind: UnattendedInstallConfig
      provisioning:
        diskSelector:
          match: disk.dev_path == "/dev/nvme0n1"
  - name: hostname
    inline: |
      apiVersion: v1alpha1
      kind: HostnameConfig
      hostname: magic-8-balls
  - name: kexec-disable
    file: patches/kexec-disable.yaml
  - name: gc-threshold
    file: patches/gc-threshold.yaml
  - name: cloudflared-quic
    file: patches/cloudflared-quic.yaml
systemExtensions:
  - siderolabs/intel-ucode
  - siderolabs/i915
---
kind: Machine
name: 4c4c4544-0052-4e10-8054-b3c04f4e5932
patches:
  - name: install-disk
    inline: |
      apiVersion: v1alpha1
      kind: UnattendedInstallConfig
      provisioning:
        diskSelector:
          match: disk.dev_path == "/dev/nvme0n1"
  - name: hostname
    inline: |
      apiVersion: v1alpha1
      kind: HostnameConfig
      hostname: omniscient-cue-ball
  - name: kexec-disable
    file: patches/kexec-disable.yaml
  - name: gc-threshold
    file: patches/gc-threshold.yaml
  - name: cloudflared-quic
    file: patches/cloudflared-quic.yaml
systemExtensions:
  - siderolabs/intel-ucode
  - siderolabs/i915
---
kind: Machine
name: 4c4c4544-0052-4810-8054-b3c04f4e5932
patches:
  - name: install-disk
    inline: |
      apiVersion: v1alpha1
      kind: UnattendedInstallConfig
      provisioning:
        diskSelector:
          match: disk.dev_path == "/dev/nvme0n1"
  - name: hostname
    inline: |
      apiVersion: v1alpha1
      kind: HostnameConfig
      hostname: flourite-octet
  - name: kexec-disable
    file: patches/kexec-disable.yaml
  - name: gc-threshold
    file: patches/gc-threshold.yaml
  - name: cloudflared-quic
    file: patches/cloudflared-quic.yaml
systemExtensions:
  - siderolabs/intel-ucode
  - siderolabs/i915
---
kind: Machine
name: ad064900-a236-11f1-926b-11bbce7a6b00
patches:
  - name: install-disk
    inline: |
      apiVersion: v1alpha1
      kind: UnattendedInstallConfig
      provisioning:
        diskSelector:
          match: disk.dev_path == "/dev/nvme0n1"
  - name: hostname
    inline: |
      apiVersion: v1alpha1
      kind: HostnameConfig
      hostname: spidermom
  - name: limit-ephemeral-volume
    inline: |
      apiVersion: v1alpha1
      kind: VolumeConfig
      name: EPHEMERAL
      provisioning:
        maxSize: 240GiB
  - name: ai-models-volume
    inline: |
      apiVersion: v1alpha1
      kind: UserVolumeConfig
      name: ai-models
      provisioning:
        diskSelector:
          match: disk.transport == 'nvme'
        minSize: 240GiB
        maxSize: 500GiB
  - name: nvidia
    file: patches/nvidia.yaml
systemExtensions:
  - siderolabs/nonfree-kmod-nvidia-lts
  - siderolabs/nvidia-container-toolkit-lts
