---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: backend-cloudflare
  namespace: burrito-project-default
spec:
  secretStoreRef:
    kind: SecretStore
    name: tf
  target:
    creationPolicy: Owner
  data:
    - secretKey: AWS_ACCESS_KEY_ID
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
        key: backend-cloudflare
        property: keyID
    - secretKey: AWS_SECRET_ACCESS_KEY
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
        key: backend-cloudflare
        property: applicationKey
---
apiVersion: config.terraform.padok.cloud/v1alpha1
kind: TerraformRepository
metadata:
  name: cloudflare
  namespace: burrito-project-default
spec:
  repository:
    url: https://github.com/jdmcmahan/cloudflare-tf.git
    secretName: github-token
  terraform:
    enabled: true
  overrideRunnerSpec:
    env:
      - name: AWS_REQUEST_CHECKSUM_CALCULATION
        value: when_required
      - name: AWS_RESPONSE_CHECKSUM_VALIDATION
        value: when_required
      - name: TF_VAR_onepassword_connect_url
        value: http://onepassword-connect.onepassword.svc.cluster.local:8080
      - name: TF_VAR_onepassword_connect_token
        valueFrom:
          secretKeyRef:
            name: onepassword-connect-token-tf
            key: token
    envFrom:
      - secretRef:
          name: onepassword-connect-token-tf
      - secretRef:
          name: backend-cloudflare
---
apiVersion: config.terraform.padok.cloud/v1alpha1
kind: TerraformLayer
metadata:
  name: cloudflare-root
  namespace: burrito-project-default
spec:
  branch: "main"
  repository:
    name: cloudflare
    namespace: burrito-project-default
