on:
  push:
    paths:
      - 'infrastructure/sidero/omni/resources/**'
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    name: Sync cluster templates with Sidero Omni
    steps:
      - name: Run omnictl
        uses: jdmcmahan/omnictl-action@main
        with:
          omni-endpoint: ${{ secrets.OMNI_ENDPOINT }}
          omni-service-account-key: ${{ secrets.OMNI_SERVICE_ACCOUNT_KEY }}
          command: 'omnictl --version'
