on:
  workflow_dispatch:

jobs:
  update-servers:
    runs-on: ubuntu-latest
    container: qmcgaw/gluetun:v3.40.0
    name: Fetch updated servers list
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run gluetun update utility
        run: /gluetun-entrypoint update -enduser -providers mullvad

      - name: Upload servers.json
        uses: actions/upload-artifact@v4
        with:
          name: servers.json
          path: /gluetun/servers.json
          retention-days: 1
