on:
  workflow_dispatch:

jobs:
  get-servers:
    name: Fetch updated servers list
    runs-on: ubuntu-latest
    container: qmcgaw/gluetun:v3.40.0
    steps:
      - name: Run gluetun update utility
        run: /gluetun-entrypoint update -enduser -providers mullvad

      - name: Upload servers.json
        uses: actions/upload-artifact@v4
        with:
          name: servers
          path: /gluetun/servers.json
          retention-days: 1

  update-config:
    name: Update gluetun configuration in repo
    needs: get-servers
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download updated servers list
        uses: actions/download-artifact@v4
        with:
          name: servers
          path: apps/media/seedbox/qbittorrent/config

      - name: Test output
        run: ls -R apps/media/seedbox/qbittorrent/config
