---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - "namespace.yaml"
  - "https://github.com/NVIDIA/gpu-operator//deployments/gpu-operator/crds/nvidia.com_clusterpolicies.yaml?ref=v26.7.0"
  - "https://github.com/NVIDIA/gpu-operator//deployments/gpu-operator/crds/nvidia.com_nvidiadrivers.yaml?ref=v26.7.0"
  - "https://github.com/NVIDIA/gpu-operator//deployments/gpu-operator/crds/nvidia.com_gpuclusters.yaml?ref=v26.7.0"

helmCharts:
  - name: gpu-operator
    repo: https://helm.ngc.nvidia.com/nvidia
    version: v26.7.0
    releaseName: gpu-operator
    namespace: nvidia
    valuesFile: values.yaml
